
// english
export const EN = {
  // Header
  "dial.112": "Dial 112",
  "citizen.portal": "Citizen Portal",
  "e.office": "E-Office",
  "nic.email": "NIC Email",
  sss: "SSS",
  "skip.content": "Skip to Content",
  "font.size": "Font Size",
  "high.contrast": "High Contrast",
  "light.mode": "Light",
  "dark.mode": "Dark",
  language: "Language",
  marathi: "मराठी",
  english: "English",
  "title": "police Communication and Information <br/> Technology Department, pune",
  // Department Info
  "dept.name.marathi": "पोलीस दळणवळण व माहिती तंत्रज्ञान विभाग",
  "dept.name.english":
    "Police Communication and Information Technology Department",
  "dept.subtitle": "Maharashtra State Official Website",
  //welfare
  "welfare.title": "Welfare Activities",
  "welfare.accordionTitle": "Welfare Activities",
  "welfare.viewButton": "View",
  "welfare.detailsButton": "Details",
  "welfare.item1.title": "Museum – Evolution in Wireless",
  "welfare.item2.title": "Canteen – Muktai",
  "welfare.item3.title": "Badminton Hall – Sant Tukaram Sankul",
  "welfare.item4.title": "Senior Officers Mess – Dnyaneshwari",
  "welfare.item5.title": "Junior officer's Mess – Sanchar",
  "welfare.item6.title": "Open Museum – Aryabhatta Garden",
  "welfare.item7.title": "Parade ground",
  "welfare.item8.title": "Solar Electrification project",
  "welfare.item9.title": "Rain Water Harvesting",
  "welfare.item10.title": "Maharashtra Police Wireless Welfare Complex and Convention Centre",

  // Navigation
  "nav.home": "Home",
  "nav.about": "About",
  "nav.directorDesk": "From Director’s Desk",
  "nav.formerDirectors": "Former Directors",
  "nav.hierarchy": "Hierarchy",
  "nav.aboutDepartment": "About Department",
  "nav.offices": "Offices in Headquarters",
  "nav.ranks": "Ranks",
  "nav.welfare": "Welfare Activities",

  "nav.citizens": "Citizen Corner",
  "nav.citizenCorner": "Citizen Corner",
  "nav.policeCorner": "Police Corner",
  "nav.pressRelease": "Press Release",
  "nav.rti": "RTI",
  "nav.gazette": "Gazette",
  "nav.officersList": "List of Officers",
  "nav.promotionOrders": "Promotion Orders",
  "nav.transfers": "Transfers",
  "nav.gradationList": "Gradation List",
  "nav.strategySupport": "Strategy Support System",
  "nav.positiveStories": "Positive Stories",
  "nav.police_corner": "Police Corner",
  "nav.tenders": "Tender List",
  "nav.recruitments": "Recruitments",

  "nav.media": "Media",
  "nav.gallery": "Photo Gallery",

  "nav.contact": "Contact",
  "nav.contactUs": "Contact Us",




  // Hero Section
  "police.helpline": "Police Helpline",
  "medical.helpline": "Medical Emergency",
  "women.safety": "Women Safety Helpline",
  "welcome.title": "Welcome to Maharashtra Police Communication, Information Technology and Transportation Department",
  "welcome.message":
    "Committed to leveraging cutting-edge technology for enhanced public safety and efficient police operations across Maharashtra State.",
  "director.desk": "From Director's Desk",
  "director.caption": `"Our commitment to modernizing police infrastructure through
                  cutting-edge communication and information technology
                  continues to strengthen Maharashtra's security framework..."`,
  "read.more": "Read More",

  // Hero slider images

  "hero.modernTech.title": "Modern Police Technology",
  "hero.modernTech.subtitle": "Enhancing Public Safety Through Innovation",

  "hero.digitalGovernance.title": "Digital Governance",
  "hero.digitalGovernance.subtitle": "Transparent and Efficient Police Services",

  "hero.communityPolicing.title": "Community Policing",
  "hero.communityPolicing.subtitle": "Building Trust Through Technology",

  //DIRECTONFO
  "a1.back": "Back to Home",

  "a2.desk": "From Director’s Desk",
  "a2.name": "Mr. Deepak Shivanand Pandey",
  "a2.desg": "Additional Director General of Police & Director",
  "a2.dept": "Police Communication & IT Department",
  "a2.loc": "Maharashtra State, Pune",

  "b1.intro": "The Police Wireless Department prior to Police Communication and Information Technology Department typically handles communication systems used by law enforcement authority that is Maharashtra State Police. This includes managing radio frequencies, dispatching officers, and ensuring secure and efficient communication between police units in the field.",
  "b1.hl": "Uninterrupted 24×7 communication",
  "b1.intro2": "system is provided by our Department.",
  "b1.role": "The Police Communication and Information Technology Department plays a vital role in policing by ensuring effective communication and coordination among officers with key functions such as:",

  "c1.f1.t": "Real-time Communication",
  "c1.f1.d": "facilitates immediate contact between officers and dispatch.",
  "c1.f2.t": "Situational Awareness",
  "c1.f2.d": "provides updates on ongoing situations for better decisions.",
  "c1.f3.t": "Emergency Response",
  "c1.f3.d": "enables faster deployment during emergencies.",
  "c1.f4.t": "Data Transmission",
  "c1.f4.d": "supports secure sharing of critical intelligence.",
  "c1.f5.t": "Safety and Security",
  "c1.f5.d": "protects sensitive information and officer safety.",

  "b1.crisis": "The Koyna earthquake (1967) and Killari earthquake (1993) caused significant devastation in Maharashtra. The Mumbai floods (2005) and 26/11 terrorist attack highlighted the importance of communication. During such crises, when private networks collapsed, wireless systems kept police connected, enabling life-saving coordination.",
  "b1.conc": "Effective wireless communication is the backbone of public safety and operational excellence in policing.",


  // Director Info
  "director.name": "Shri. Deepak Shivanand Pandey (IPS)",
  "director.rank": "Additional Director General of Police and Director,",
  "director.designation":
    "Police Communication, Information Technology and Transportation Department, Maharashtra State, Pune.",

  // Emergency Contacts
  "emergency_contacts": "Emergency Contacts",
  "emergency.police": "Police Emergency",
  "emergency.fire": "Fire Emergency",
  "emergency.ambulance": "Ambulance",
  "emergency.disaster": "Disaster Management",
  "emergency.women": "Women Helpline",
  "emergency.child": "Child Helpline",
  "emergency.single": "Single Emergency Number",

  "type.police": "Police",
  "type.fire": "Fire",
  "type.medical": "Medical",
  "type.disaster": "Disaster",
  "type.women": "Women Safety",
  "type.child": "Child Care",
  "type.allInOne": "All-in-One",

  // Government Updates
  "govt.updates": "Government Updates",
  "bulletins": "Bulletins / Orders / Instructions",
  "tenders.section": "Tenders",
  "view.all": "View All",

  "bulletin.cybercrimePortal": "PP RESULT RM, ELE., WO – 2024",
  "bulletin.digitalEvidence": "AANDYANKIT KASHAT UPSHTIT RAHANEBABAT",
  "bulletin.emergencyProtocol": "KARYMUKT KARNEBABAT",
  "bulletin.auditResults": "SHUDHIPATAK GT – (PC-ASI)-2024",

  "badge.new": "New",
  "badge.important": "Important",
  "badge.update": "Update",
  "badge.report": "Report",

  // tenders
  "tender.communicationEquipment": "Supply and Installation of Communication Equipment",
  "tender.mobileApp": "Development of Mobile Application for Citizen Services",
  "tender.serverMaintenance": "Annual Maintenance of Server Infrastructure",

  "tender.status.open": "Open",
  "tender.status.closingSoon": "Closing Soon",

  //FORMERDIRECOTR
  "fd.back": "Back",
  "fd.title": "Former Directors of Department",

  "fd.d1.name": "Shri. Sunil Ramanand IPS",
  "fd.d1.designation": "Addl. D.G.P.",
  "fd.d1.tenure": "2021-2024",

  "fd.d2.name": "Shri. Retesh Kumaarr IPS",
  "fd.d2.designation": "Addl. D.G.P.",
  "fd.d2.tenure": "2016-2021",

  "fd.d3.name": "Shri. Jagannath IPS",
  "fd.d3.designation": "Addl. D.G.P.",
  "fd.d3.tenure": "2014-2016",

  "fd.d4.name": "Shri. Suresh Kakkar IPS",
  "fd.d4.designation": "Addl. D.G.P.",
  "fd.d4.tenure": "2012-2014",

  "fd.d5.name": "Shri. P.P.P. Sharma IPS",
  "fd.d5.designation": "Addl. D.G.P.",
  "fd.d5.tenure": "2008-2011",

  "fd.d6.name": "Shri. B.T. Nghinglova IPS",
  "fd.d6.designation": "Addl. D.G.P.",
  "fd.d6.tenure": "2007-2008",

  "fd.d7.name": "Shri. P.T. Lohar IPS",
  "fd.d7.designation": "Addl. D.G.P.",
  "fd.d7.tenure": "2004-2007",

  "fd.d8.name": "Shri. P. K. Joshi IPS",
  "fd.d8.designation": "SPL I.G.P. 2000-2003 | Addl. D.G.P. 2003-2004",
  "fd.d8.tenure": "2000-2004",

  "fd.d9.name": "Shri. A. D. Jog SPS",
  "fd.d9.designation": "D.I.G. 1979-1987 | SPL I.G. 1989-1999",
  "fd.d9.tenure": "1979-1999",

  "fd.d10.name": "Shri. S. M. Nabar",
  "fd.d10.designation": "SP 1948-1968 | D.I.G.P. 1968-1978",
  "fd.d10.tenure": "1948-1978",

  "fd.d11.name": "Shri. L. A. Paddon Row IP",
  "fd.d11.designation": "SP M. T. & W/L",
  "fd.d11.tenure": "1947-1948",

  "fd.d12.name": "Shri. E. A. Dodwell IP",
  "fd.d12.designation": "SP M. T. & W/L",
  "fd.d12.tenure": "1946-1947",

  // Events
  "latest.events": "Latest Events",
  "photo.gallery": "Photo Gallery",
  "view.all.events": "View All Events",
  "view.gallery": "View Gallery",
  "event.pcit.upgrades": "Independence Celebration in PCIT",
  "event.marvel.aiProject": "Republic Day Celebration in PCIT",
  "event.dial112": "Dial 112 Integrated Emergency Response",
  "event.cyber.centerLaunch": "Cyber Command & Control Centre Launch",

  "event.location.headquarters": "Headquarters",
  "event.location.statewide": "Statewide",
  "event.location.maharashtra": "Headquarters",
  "event.location.mumbai": "Mumbai",
  "gallery.videoAvailable": "Video Gallery Available",
  "gallery.viewAllPhotos": "View All Photos",

  //HEIRARCHY
  "h1.back": "Back",
  "h1.title": "Hierarchy",
  "h1.alt": "Hierarchy Chart",

  // Emergency Helplines 
  "emergency.message": "In case of emergency, dial these numbers for immediate assistance",
  "helpline.child": "Child Helpline",
  "helpline.senior": "Senior Citizen Helpline",
  "helpline.roadAccident": "Road Accident Emergency",
  "helpline.fire": "Fire Services",
  "helpline.disaster": "Disaster Management",
  "helpline.antiCorruption": "Anti-Corruption Helpline",
  "emergency.helpline": "Emergency Helplines",

  "metro.helpline": "Mumbai Metro",
  "rest.helpline": "Rest of Maharashtra",
  "helpline.tapToCall": "Tap to Call",

  "additionalHelplines.header": "Other Important Helpline Numbers",

  "important.note.title": "Important Note:",
  "important.note.message": "These helpline numbers are available 24/7. For non-emergency police services, you can also visit your nearest police station or use our online portal.",

  "emergency.tips.title": "During Emergency",
  "emergency.tips.item1": "Stay calm and speak clearly",
  "emergency.tips.item2": "Provide your exact location",
  "emergency.tips.item3": "Describe the nature of emergency",
  "emergency.tips.item4": "Follow operator's instructions",
  "emergency.tips.item5": "Keep your phone fully charged and accessible",


  "smart.features.title": "Smart Features",
  "smart.features.item1": "SMS to 112 for speech/hearing impaired",
  "smart.features.item2": "Location tracking for faster response",
  "smart.features.item3": "Multi-language support available",
  "smart.features.item4": "Integration with emergency services",

  //ABOUTDEPT
  "hx_back": "Back to Home",
  "hx_photoAlt": "History of Police Wireless",
  "hx_title": "History of Police Wireless Communication Department",
  "hx_intro": "Established in 1946, the Department has evolved from WWII wireless sets to cutting-edge satellite and IP-based networks ensuring secure, real-time communication across Maharashtra.",

  "hx_1946_title": "1946 – Foundation",
  "hx_1946_desc": "Department established in Mumbai during pre-independence. Wireless started with WWII sets; 13 districts linked to Pune HQ.",

  "hx_1947_title": "1947 – First Leadership",
  "hx_1947_desc": "After independence, Mr. N.M. Kamte became the first Special IGP. Wireless Dept. separated administratively, led by Mr. S.M. Nabar.",

  "hx_tableTitle": "Sanctioned Posts",
  "hx_table_sr": "SR NO",
  "hx_table_desig": "DESIGNATION",
  "hx_table_posts": "SANCTION POSTS",
  "hx_prev": "Previous",
  "hx_next": "Next",
  "hx_page": "Page",
  "hx_of": "of",
  "hx_summary": "SUMMARY TOTAL:",
  //OFFICERINHQ



  // goverment links
  "acb_maharashtra": "Anti-Corruption Bureau, Maharashtra State",
  "acb_full_name": "Visit Anti-Corruption Bureau Maharashtra website",
  "mpa_nashik": "Maharashtra Police Academy",
  "mpa_full_name": "Visit Maharashtra Police Academy website",
  "aaple_sarkar": "Aaple Sarkar - Maharashtra Government Portal",
  "aaple_sarkar_desc": "Visit Aaple Sarkar Maharashtra Government Services Portal",
  "maharashtra_police": "Maharashtra Police",
  "maharashtra_police_desc": "Visit Maharashtra Police official website",
  "startup_india": "Startup India Initiative",
  "startup_india_desc": "Visit Startup India government initiative website",
  "digital_india": "Digital India Initiative",
  "digital_india_desc": "Visit Digital India government initiative website",
  "government_partners": "Government Partners and Related Websites",
  "carousel_instructions": "Use arrow keys to navigate through government partner website links",

  //oofer in hq
  "oh_back": "Back to Home",
  "oh_title": "Officers in Headquarters",

  "oh_admin_title": "Administrative Office",
  "oh_admin_incharge": "Office Superintendent (OS)",
  "oh_admin_A_title": "“A” Branch",
  "oh_admin_A_item1": "RTI",
  "oh_admin_A_item2": "Yearly Administrative Report",
  "oh_admin_A_item3": "Budget, Annual Inspection",
  "oh_admin_A_item4": "BMI etc Govt. Quarters distribution / maintenance / repairs",
  "oh_admin_A_item5": "NE line/Medical/ TA/ MSEB/ MKAY / Telephone / MT / Fuel/ etc Bills payment order",
  "oh_admin_B_title": "“B” Branch",
  "oh_admin_B_item1": "Welfare",
  "oh_admin_B_item2": "Income Tax",
  "oh_admin_B_item3": "GST",
  "oh_admin_E_title": "“E” Branch",
  "oh_admin_E_item1": "MAT Cases",
  "oh_admin_E_item2": "Enquiries of Wireless Officers / Men",
  "oh_admin_E_item3": "PC to PSI Gradation List",
  "oh_admin_E_item4": "Promotions & Transfers",
  "oh_admin_E_item5": "Preparation of Service Sheets",
  "oh_admin_E_item6": "Maintaining & updating vacancy statements",
  "oh_admin_E_item7": "Scheduling Classification / Proficiency Exams",
  "oh_admin_E_item8": "Processing & follow-up of Recruitment / RR process",
  "oh_admin_D_title": "“D” Branch",
  "oh_admin_D_item1": "Procurement & purchase of spares/accessories via GEM (NIC portal)",
  "oh_admin_D_item2": "Tender process for wireless equipment purchases by DGP MS Mumbai",

  "oh_tech_title": "Technical Branch",
  "oh_tech_incharge": "DYSP (Admin)",
  "oh_tech_item1": "Supervises day-to-day working of administrative & technical branches",
  "oh_tech_item2": "Administrative branches: A, B, D, E, Accounts",
  "oh_tech_item3": "Technical branches: Bandobast, Planning, License, Welfare, Home PI, SSS",
  "oh_tech_item4": "Bandobast Branch: Provides manpower & equipment, maintains records, inspection schedules",
  "oh_tech_item5": "Planning Branch: Prepares proposals, conducts meetings, coordinates with Pol-4 & DGP Mumbai",
  "oh_tech_item6": "Home PI: Manages MT section, MAT cases, RTI work",
  "oh_tech_item7": "Welfare Branch: Oversees Dnyaneshwari Sr. Officers Mess, Sanchar Hostel, etc.",
  "oh_tech_item8": "SSS Branch: Trials, development, & improvisation for police communication",

  "oh_dev_title": "Development Section",
  "oh_dev_item1": "Computer Section: Technical specs, NIC email, CIPHER maintenance, video conferences, e-Office implementation",
  "oh_dev_item2": "Radio Communication Section: Repairs, condemnation, testing of wireless sets, repeaters",
  "oh_dev_item3": "Line Communication Section: Telephone Exchanges, IP/Digital Units, cable maintenance, evaluation of new purchases",
  "oh_dev_item4": "Electrical Section: Chargers, inverters, UPS, DG sets, solar chargers, batteries maintenance & evaluation",
  "oh_dev_item5": "Installation Branch: DG sets, streetlights, air conditioners maintenance, local purchases, water & electricity bills",
  "oh_dev_item6": "Store Section: Handling & record-keeping of store material, test reports & sample records",

  "oh_vsat_title": "V-SAT Section",
  "oh_vsat_incharge": "DYSP",
  "oh_vsat_item1": "Monitoring daily status of all Polnet stations in Maharashtra",
  "oh_vsat_item2": "Providing technical guidance to Polnet units (coordination with DCPW, New Delhi)",
  "oh_vsat_item3": "Ensuring smooth operation of Polnet HQ Pune station",
  "oh_vsat_item4": "Preparing technical specifications for Polnet & CCTV equipment",

  "oh_store_title": "Store Sections",
  "oh_store_item1": "Store Section I (SM I): Distribution of purchased wireless equipment, deployment for bandobast, dispatch defective equipment under warranty, maintain reserve stock & BER depositions, auction process handling",
  "oh_store_item2": "Store Section II (SM II): Distribution of wireless spares, deployment of software/cables for digital wireless equipment, disposal of unserviceable material, maintaining ledgers",
  "oh_store_item3": "Store Section III (SM III): Distribution of cables, antennas, exchange cards, manuals, deployment of software/cables for analog wireless equipment, disposal of condemned equipment & masts, maintaining ledgers",

  "oh_committee_title": "Committee Section",
  "oh_committee_item1": "Conducts equipment/accessories sample checks",
  "oh_committee_item2": "Collection of Test/Receipt Reports",

  "oh_test_title": "Test Cell",
  "oh_test_item1": "Testing wireless equipment for bandobast units",
  "oh_test_item2": "Maintenance of central store systems",

  "oh_central_title": "Central Store Admin Section",
  "oh_central_item1": "Inward/outward correspondence entries",
  "oh_central_item2": "Record-keeping & letter distribution",
  "oh_central_item3": "Assisting store sections in workload",

  "oh_cipher_title": "Cipher Branch",
  "oh_cipher_incharge": "DYSP (Cipher)",
  "oh_cipher_item1": "Custodian of Cipher documents/materials for Maharashtra State",
  "oh_cipher_item2": "Courier arrangements with DCPW New Delhi (quarterly)",
  "oh_cipher_item3": "Coordination with Crypto Centers in Maharashtra, Goa, Daman",
  "oh_cipher_item4": "Conducting Basic Cipher Courses in Pune",
  "oh_cipher_item5": "Maintenance of cipher documents, courses, & computer repairs",
  "oh_cipher_item6": "Loading cipher programs at Crypto Centers",
  "oh_cipher_item7": "Inspections of Crypto Centers across Maharashtra",

  "oh_license_title": "License Branch",
  "oh_license_incharge": "DYSP (License)",
  "oh_license_item1": "Apply for radio licenses",
  "oh_license_item2": "Pay spectrum charges to Govt. of India",
  "oh_license_item3": "Apply for new frequencies (HF/VHF/UHF)",
  "oh_license_item4": "Distribute sanction network letters",
  "oh_license_item5": "Submit periodic traffic returns (monthly, 6-monthly, yearly)",
  "oh_license_item6": "Prepare call signs for Ministers, VVIPs, VIPs, Senior Officers",

  "oh_traffic_title": "Traffic Branch",
  "oh_traffic_incharge": "DYSP (Traffic)",
  "oh_traffic_item1": "Conduct inspections of 64 Polnet stations, 46 HF stations, 64 TAPs",
  "oh_traffic_item2": "Preparation of call signs for VVIPs, ministers, officers",
  "oh_traffic_item3": "Conduct & supervise IT proficiency exams (written/practical)",
  "oh_traffic_item4": "Supervision of traffic cases from Central Check Office, Pune",
  "oh_traffic_item5": "Scrutiny of security breach cases on VHF channel",

  // Footer
  "quick.links": "Quick Links",
  "important.links": "Important Links",
  "contact.info": "Contact Information",
  "visitor.stats": "Visitor Statistics",
  address: "Address",
  phone: "Phone",
  email: "Email",
  copyright:
    "© 2025 Police Communication & IT Department, Maharashtra State. All rights reserved.",
  "developed.by": "Designed & Developed by Dreamcare Solutions",
  "dept.address": "Police Communication & IT Department,<br />Maharashtra State Police Headquarters,<br />Mumbai - 400001"
  ,

  //rank

  "backToHome": "Back to Home",
  "ranks.title": "Ranks",
  "ranks.subtitle": "List of Ranks and Designations in Police Communication and Information Technology Department",
  "ranks.seePDF": "See the Whole PDF",
  "ranks.rank1.title": "Addl. DGP & Director Police Communication, Information Technology & Transportation, M.S. Pune",
  "ranks.rank1.description": "Leads the entire department, sets strategic direction, ensures coordination across all units, and oversees communication, IT, and transportation functions statewide.",
  "ranks.rank2.title": "Deputy Inspector General of Police Communication & Information Technology, M.S. Pune",
  "ranks.rank2.description": "Assists the Director in managing statewide operations, supervises technical teams, and ensures adherence to policies and standards.",
  "ranks.rank3.title": "Additional Commissioner of Police Communication & Information Technology, M.S. Mumbai",
  "ranks.rank3.description": "Leads Mumbai operations, manages critical IT infrastructure, ensures secure communications, and coordinates with local law enforcement units.",
  "ranks.rank4.title": "Supdt. Of Police Communication & Information Technology",
  "ranks.rank4.description": "Supervises field units, monitors wireless systems, coordinates departmental activities, and ensures smooth day-to-day operations.",
  "ranks.rank5.title": "Deputy Commissioner of Police Communication & Information Technology",
  "ranks.rank5.description": "Oversees technical teams, manages operations, and provides guidance for implementing IT and communication strategies.",
  "ranks.rank6.title": "Deputy Supdt. Of Police /Asst. Commissioner of Police",
  "ranks.rank6.description": "Handles daily technical operations, staff assignments, troubleshooting, and ensures compliance with departmental protocols.",
  "ranks.rank7.title": "Police Inspector (PI)",
  "ranks.rank7.description": "Supervises teams, monitors field communications, enforces regulations, and reports technical issues to senior officers.",
  "ranks.rank8.title": "Police Sub-Inspector (PSI)",
  "ranks.rank8.description": "Maintains wireless networks, supports investigations, and ensures effective communication within the unit.",
  "ranks.rank9.title": "ASI (Senior Technical Officer)",
  "ranks.rank9.description": "Leads technical projects, audits systems, trains junior staff, and ensures technical excellence across operations.",
  "ranks.rank10.title": "HC (Technical Officer)",
  "ranks.rank10.description": "Operates and maintains technical equipment, supports wireless and IT operations, and ensures continuous service.",
  "ranks.rank11.title": "ASI (Senior Technical Assistant)",
  "ranks.rank11.description": "Assists senior officers in technical tasks, system maintenance, and coordinates with field units.",
  "ranks.rank12.title": "HC (Technical Assistant Grade II)",
  "ranks.rank12.description": "Handles administrative support, technical documentation, and assists in communication tasks.",
  "ranks.rank13.title": "PN (Technical Assistant Grade I)",
  "ranks.rank13.description": "Performs day-to-day technical assistance, monitors equipment, and supports operations.",
  "ranks.rank14.title": "PC (Technical Assistant)",
  "ranks.rank14.description": "Supports operations under supervision, assists in communication tasks, and maintains records.",
  "ranks.rank15.title": "ASI (Driver)",
  "ranks.rank15.description": "Provides transportation for high-ranking officers and supports operational logistics.",
  "ranks.rank16.title": "HC (Driver)",
  "ranks.rank16.description": "Ensures reliable transport for staff and equipment, assists in logistical planning.",
  "ranks.rank17.title": "PN (Driver)",
  "ranks.rank17.description": "Supports vehicle operations and transportation coordination within the department.",
  "ranks.rank18.title": "PC (Driver)",
  "ranks.rank18.description": "Handles routine driving duties, transport coordination, and ensures timely mobility of personnel.",

  // Helpline

  "police.100": "Police - 100/112",
  "medical.108": "Medical - 108",
  "women.103": "Women Safety - 103/1091",
  "maha.police": "Maharashtra Police",
  "rti": "Right to Information",
  "public.grievances": "Public Grievances",
  "footer.privacyPolicy": "Privacy Policy",
  "footer.termsOfUse": "Terms of Use",
  "footer.accessibility": "Accessibility",

  // Press Release Page
  "back.home": "Back to Home",
  "press.title": "Press Releases",
  "press.subtitle": "Positive developments and ongoing projects in the Maharashtra Police Wireless Department",
  "press.tech.title": "Technological Upgrades",
  "press.tech.description": "Independence Day was celebrated with great enthusiasm in the Police Communication and Information Technology Department. Officers and staff participated in the flag hoisting, national anthem, and cultural programs, spreading the message of patriotism and unity.",
  "press.ai.title": "AI-Powered Policing - MARVEL Project",
  "press.ai.description": "Republic Day was celebrated with great enthusiasm in the Police Communication and Information Technology Department. Officers and staff participated in the flag hoisting, national anthem, and patriotic programs, highlighting the values of the Constitution, patriotism, and unity.",
  "press.emergency.title": "Enhanced Emergency Response - Dial 112",
  "press.emergency.description": "The 'Dial 112' emergency system integrates police (100), fire (101), and ambulance (108) services into a single number. Using advanced tracking and dispatch technology, response times are drastically reduced, saving lives and improving public safety.",
  "press.cyber.title": "New Cyber Command Center",
  "press.cyber.description": "In October 2024, a new Cyber Command and Control Centre was launched. Equipped with advanced forensic tools and AI-based threat detection, it allows the police to combat cybercrime efficiently and ensures digital safety for citizens and critical infrastructure.",

  // RTI Page
  "rti.title": "RTI (Right to Information)",
  "rti.subtitle": "Information and procedures for citizens under the Right to Information Act",
  "rti.pio.title": "Public Information Officer (PIO) Details",
  "rti.pio.description": "Contact information for the designated PIOs and Appellate Authorities within the Police Communication & IT Department is provided here. Citizens can reach out directly for submitting RTI requests or seeking clarifications.",
  "rti.procedure.title": "RTI Application Procedure",
  "rti.procedure.description": "Step-by-step guide on filing an RTI application including the proper format, required details, and applicable fees. Ensure all fields are correctly filled for faster processing.",
  "rti.portal.title": "Online RTI Portal Link",
  "rti.portal.description": "Submit RTI applications electronically through the official portals. Maharashtra RTI Portal and Government of India RTI online portals are linked for citizen convenience.",
  "rti.frequent.title": "Frequently Requested Information",
  "rti.frequent.description": "Access commonly requested documents such as organizational structure, budget details, citizen charters, and departmental manuals. This improves transparency and eases information retrieval.",
  "rti.manual.title": "RTI Act Manual",
  "rti.manual.description": "Download or view the full RTI Act, 2005 and official guidelines for reference. Citizens are encouraged to familiarize themselves with their rights and responsibilities under the Act.",
  "rti.appeal.title": "Appeal Process",
  "rti.appeal.description": "If the applicant is unsatisfied with the response, follow the appeal procedure within the prescribed timelines. Details for submitting first and second appeals, along with contact information for appellate authorities, are provided.",

  // Tenders Page
  "tenders.title": "Tenders & Procurement",
  "tenders.subtitle": "Official procurement notices and contract opportunities for the Maharashtra Police Wireless Department",
  "tenders.active.title": "Active Tenders",
  "tenders.archived.title": "Archived / Completed Tenders",
  "tenders.procurement.title": "Tender-Related Information",
  "tenders.ref": "Tender Ref",
  "tenders.deadline": "Deadline",
  "tenders.closedOn": "Closed On",
  "tenders.viewDocument": "View Tender Document",

  // Active Tenders
  "tenders.active.radios.title": "Procurement of Digital Mobile Radios",
  "tenders.active.radios.description": "Supply of high-performance digital mobile radios for state-wide police communication.",

  // Archived Tenders
  "tenders.archived.spares.title": "Wireless Equipment Spares",
  "tenders.archived.computers.title": "Computers & Networking Equipment",

  // Procurement Info
  "tenders.procurement.general.title": "General Procurement Details",
  "tenders.procurement.general.description": "All procurement processes are handled by the 'D' Branch, including procurement of spares and accessories via the GEM portal.",
  "tenders.procurement.technical.title": "Technical Specifications",
  "tenders.procurement.technical.description": "Specifications for equipment such as Digital Mobile Radios, Repeaters, Antennas, Computers, and Telephone Exchanges are prepared and evaluated by the R&D section.",
  "tenders.procurement.auction.title": "Auction Notices",
  "tenders.procurement.auction.description": "Information on auctions of condemned or unserviceable equipment (wireless sets, batteries) conducted by the Central Store.",

  "recruit.title": "Recruitments",
  "recruit.subtitle": "Information about current and upcoming job opportunities in the Maharashtra Police Wireless Department",
  "recruit.notifications.title": "Recruitment Notifications",
  "recruit.notifications.description": "Official advertisements for current and upcoming job openings in the department, including positions such as ASI, HC, PC, Technical Assistants, and Drivers. Stay updated to apply for suitable roles.",
  "recruit.forms.title": "Application Forms",
  "recruit.forms.description": "Links and downloadable forms for submitting applications for departmental vacancies. Online submission portals are also provided where applicable.",
  "recruit.exams.title": "Exam Schedules",
  "recruit.exams.description": "Dates and timetables for written tests, proficiency exams, and practical assessments for various recruitment drives.",
  "recruit.results.title": "Results",
  "recruit.results.description": "Merit lists and final selection results for completed recruitments, such as 'PP RESULT RM, ELE., WO – 2024'.",
  "recruit.training.title": "Training Details",
  "recruit.training.description": "Information on training programs for selected cadets, including basic training for DySP, PSI, ASI/RM, HC/Wireless Operators, HC/Electricians, and PC/Workshop Hand.",
  "recruit.eligibility.title": "Eligibility Criteria",
  "recruit.eligibility.description": "Educational qualifications, age limits, and physical requirements for various posts to ensure all applicants meet departmental standards.",
  "recruit.proficiency.title": "Proficiency / Classification Exams",
  "recruit.proficiency.description": "Notices for internal exams that assist in promotions, such as wireless operator exams and classification tests for departmental personnel.",
  // Gallery Page
  "gallery.title": "Photo Gallery",
  "gallery.image1.caption": "Dr. APJ Abdul Kalam Innovation Center Inauguration",
  "gallery.image2.caption": "Independence Day Celebrations",
  "gallery.image3.caption": "Ashok Jog Lecture Hall Inauguration",
  "gallery.image4.caption": "DGP Inauguration",

  // Contact Page
  "contact.title": "Contact Us",
  "contact.subtitle": "Reach us via phone, email, or visit our office",
  "contact.address.title": "Office Address",
  "contact.address.line1": "Police Communication and Information Technology Department",
  "contact.address.line2": "Maharashtra State Pune",
  "contact.address.line3": "Dr. Homi Bhabha Road, Chavannagar",
  "contact.address.line4": "Pune – 411008, Maharashtra, India",
  "contact.phone.title": "Telephone",
  "contact.phone.number": "020-25652505",
  "contact.email.title": "Email",
  "contact.email.address": "dir.polwireless.pune@mahapolice.gov.in",
  "contact.map.title": "Find Us on Map",

  //listofofficer
  "back_to_home": "Back to Home",
  "export_csv": "Export CSV",
  "list_of_officers": "List of Officers",
  "seniority_ranking_description": "Seniority-wise ranking of officers and staff in the Maharashtra Police Communication & IT Department",
  "sr_no": "SR NO",
  "full_name": "Full Name",
  "designation": "Designation",
  "email1": "Email",
  "contact": "Contact",
  "csv_file_name": "maharashtra_police_employees.csv",
  "previous": "Previous",
  "next": "Next",
  "page": "Page",
  "of": "of",
  "emp_1_name": "SHRI. DEEPAK SHIVANAND PANDEY",
  "emp_1_designation": "ADGP & Dir.PCIT&T",
  "emp_2_name": "SHRI. R. RAJA",
  "emp_2_designation": "DIGP(PCIT)/SP",
  "emp_3_name": "SHRI. RAJESH RAMCHANDRA BANSODE",
  "emp_3_designation": "SP(PCIT)",
  "emp_4_name": "SHRI. SANJAY SUBHASH CHANDKHEDE",
  "emp_4_designation": "DYSP(PCIT)",
  "emp_5_name": "SHRI. ARVIND DHONDIBA ALHAT",
  "emp_5_designation": "DYSP(PCIT)",
  "emp_6_name": "SHRI. SITARAM LAXMAN JADHAV",
  "emp_6_designation": "DYSP(PCIT)",
  "emp_7_name": "SHRI. KASHINATH MANGAJI UDAR",
  "emp_7_designation": "DYSP(PCIT)",
  "emp_8_name": "SHRI. SHIVPRASAD GARIBA UIKEY",
  "emp_8_designation": "DYSP(PCIT)",
  "emp_9_name": "SHRI. SUNIL VITTHALRAO KUMBHRE",
  "emp_9_designation": "DYSP(PCIT)",
  "emp_10_name": "SHRI. NITIN PRABHAKAR JOSHI",
  "emp_10_designation": "DYSP(PCIT)",
  "emp_11_name": "SHRI. RATAN KHANDERAO DHOKLE",
  "emp_11_designation": "PI(PCIT)",
  "emp_12_name": "SHRI. KORE MAHINDRA",
  "emp_12_designation": "PI(PCIT)",
  "emp_13_name": "SHRI. MAHENDRA NARAYAN BHOSALE",
  "emp_13_designation": "PI(PCIT)",
  "emp_14_name": "SHRI. SANDEEP PRABHAKAR SASANE",
  "emp_14_designation": "PI(PCIT)",
  "emp_15_name": "SHRI. RAJARAM DATTATRAY POPALGHAT",
  "emp_15_designation": "PI(PCIT)",
  "emp_16_name": "SHRI. SANJAY SHANKARRAO CHINTEWAR",
  "emp_16_designation": "PI(PCIT)",
  "emp_17_name": "SHRI. JITENDRA BHANUJI PARDESHI",
  "emp_17_designation": "PI(PCIT)",
  "emp_18_name": "SHRI. DEEPAK SHRIKRISHNA KELKAR",
  "emp_18_designation": "PSI(PCIT)",
  "emp_19_name": "SHRI. VIKRAM VITHALRAO TAMBARE",
  "emp_19_designation": "PSI(PCIT)",
  "emp_20_name": "SHRI. SUNIL MORESHWAR POTE",
  "emp_20_designation": "PSI(PCIT)",

  // Government Publications Page
  "pubs.title": "Government Publications & Notifications",
  "pubs.subtitle": "Access official announcements, resolutions, circulars, and tenders issued by the Maharashtra Police Communication & IT Department",
  "pubs.gazette.title": "Gazette Notifications",
  "pubs.gazette.description": "Official announcements, appointments, and policy changes published in the Maharashtra Government Gazette. Citizens and employees can access notifications to stay informed about governmental and departmental developments.",
  "pubs.orders.title": "Government Orders (GRs)",
  "pubs.orders.description": "Copies of Government Resolutions relevant to the Police Communication & IT Department. These orders ensure transparency and provide official directives for operations, personnel management, and policy implementation.",
  "pubs.circulars.title": "Circulars",
  "pubs.circulars.description": "Official circulars issued by the Director General of Police (DGP) or Home Department, providing guidelines, instructions, and updates for departmental operations and staff.",
  "pubs.notifications.title": "Notifications",
  "pubs.notifications.description": "Public notices regarding administrative changes, rules, or regulations. These notifications ensure citizens and employees are aware of new protocols or modifications in policies.",
  "pubs.tenders.title": "Tender Notices",
  "pubs.tenders.description": "Official announcements of tenders related to departmental procurement and services. While some tenders are listed under a separate section, key notices are provided here for transparency and access.",

  // Privacy Policy Page
  "privacy.title": "Privacy Policy",
  "privacy.subtitle": "Protecting your personal information and ensuring data security",
  "privacy.departmentInfo": "Police Communication and Information Technology Department, Pune | Additional Director General of Police and Director, Police Communication, Information Technology and Transportation Department, Maharashtra State, Pune",
  "privacy.introduction.title": "Introduction",
  "privacy.introduction.description": "The Police Communication and Information Technology Department is committed to protecting the privacy and security of all users' personal information. This privacy policy outlines how we collect, use, and safeguard your data when you interact with our services and digital platforms.",
  "privacy.dataCollection.title": "Information We Collect",
  "privacy.dataCollection.description": "We collect necessary personal information including name, contact details, identification documents, and service-related data. This information is collected through official forms, digital platforms, and during service delivery to ensure efficient communication and service provision.",
  "privacy.dataUsage.title": "How We Use Your Information",
  "privacy.dataUsage.description": "Your information is used for providing police services, emergency response, communication purposes, and improving our services. We process data only for legitimate purposes and in compliance with applicable laws and regulations.",
  "privacy.dataSharing.title": "Information Sharing",
  "privacy.dataSharing.description": "We may share information with other government agencies, law enforcement bodies, and emergency services when required by law or for public safety purposes. Data is never sold or shared with third parties for commercial purposes.",
  "privacy.dataRetention.title": "Data Retention",
  "privacy.dataRetention.description": "We retain personal information only for as long as necessary to fulfill the purposes for which it was collected, comply with legal obligations, resolve disputes, and enforce our agreements in accordance with government regulations.",
  "privacy.userRights.title": "Your Rights",
  "privacy.userRights.description": "You have the right to access, correct, or request deletion of your personal information. You may also have the right to restrict or object to certain processing activities. Contact our Data Protection Officer for any privacy-related concerns.",
  "privacy.security.title": "Data Security",
  "privacy.security.description": "We implement appropriate technical and organizational measures to protect your personal information against unauthorized access, alteration, disclosure, or destruction. Our security protocols comply with government security standards.",
  "privacy.changes.title": "Policy Updates",
  "privacy.changes.description": "We may update this privacy policy periodically to reflect changes in our practices or legal requirements. The updated policy will be posted on our website with the effective date. We encourage you to review this policy regularly.",
  "privacy.contact.title": "Contact Information",
  "privacy.contact.description": "For any questions or concerns regarding this privacy policy or our data practices, please contact our Data Protection Officer at: Police Communication and IT Department, Pune. Email: dpo-pcit@mahapolice.gov.in | Phone: +91-20-2612-XXXX",


  // Terms of Use Page
  "terms.title": "Terms of Use",
  "terms.subtitle": "Official terms and conditions for using the Maharashtra Police Communication & IT Department website",
  "terms.deptInfo": "Police Communication and Information Technology Department, Pune. Additional Director General of Police and Director, Police Communication, Information Technology and Transportation Department, Maharashtra State, Pune.",
  "terms.acceptance.title": "Acceptance of Terms",
  "terms.acceptance.description": "By accessing and using this website, you accept and agree to be bound by these Terms of Use. If you do not agree to these terms, please refrain from using our website. These terms apply to all visitors, users, and others who access or use the service.",
  "terms.usage.title": "Permitted Use",
  "terms.usage.description": "This website is intended for legitimate purposes related to police services, information access, and citizen services. Users may access and use the content for personal, non-commercial purposes. Any unauthorized use, including but not limited to hacking, data scraping, or malicious activities, is strictly prohibited.",
  "terms.security.title": "Security Provisions",
  "terms.security.description": "Users are prohibited from attempting to compromise the security of this website, including unauthorized access to systems, data interference, or introducing malicious code. Any suspicious activities should be reported immediately to the website administrators or concerned authorities.",
  "terms.liability.title": "Limitation of Liability",
  "terms.liability.description": "The Maharashtra Police Department shall not be liable for any direct, indirect, incidental, special, or consequential damages resulting from the use or inability to use this website. While we strive to maintain accurate information, we do not guarantee the completeness or accuracy of the content.",
  "terms.privacy.title": "Privacy Policy",
  "terms.privacy.description": "Your use of this website is subject to our Privacy Policy, which explains how we collect, use, and protect your personal information. By using this website, you consent to the collection and use of information as described in the Privacy Policy.",
  "terms.conduct.title": "User Conduct",
  "terms.conduct.description": "Users must not engage in any activity that disrupts or interferes with the website's functionality. This includes uploading malicious content, spamming, or any other activity that may compromise the website's integrity or performance.",
  "terms.changes.title": "Changes to Terms",
  "terms.changes.description": "We reserve the right to modify or replace these terms at any time without prior notice. It is your responsibility to review these terms periodically for changes. Continued use of the website after any modifications constitutes acceptance of those changes.",
  "terms.contact.title": "Contact Information",
  "terms.contact.description": "For any questions regarding these Terms of Use, please contact the Police Communication & IT Department at pcit@mahapolice.gov.in or call +91-22-2262-1234.",

  // Accessibility Page
  "accessibility.title": "Accessibility Statement",
  "accessibility.subtitle": "Ensuring equal access to digital services for all citizens",
  "accessibility.deptInfo.title": "Police Communication and Information Technology Department",
  "accessibility.deptInfo.description": "Additional Director General of Police and Director, Police Communication, Information Technology and Transportation Department, Maharashtra State, Pune is committed to ensuring digital accessibility for people with disabilities. We are continually improving the user experience for everyone and applying the relevant accessibility standards.",
  "accessibility.visual.title": "Visual Accessibility",
  "accessibility.visual.description": "Our website supports screen readers, provides high contrast modes, resizable text, and alternative text for images. Users can adjust font sizes and contrast settings according to their preferences.",
  "accessibility.auditory.title": "Auditory Accessibility",
  "accessibility.auditory.description": "We provide transcripts for audio content, closed captions for videos, and visual alternatives for audio alerts. All multimedia content is designed to be accessible to users with hearing impairments.",
  "accessibility.motor.title": "Motor Accessibility",
  "accessibility.motor.description": "The website supports various input methods including keyboard navigation, voice commands, and assistive technologies. We ensure sufficient time for form completion and provide clear focus indicators.",
  "accessibility.keyboard.title": "Keyboard Navigation",
  "accessibility.keyboard.description": "All functionality is available through keyboard interfaces without requiring specific timings for individual keystrokes. The website follows logical tab order and provides skip navigation links.",
  "accessibility.language.title": "Language Support",
  "accessibility.language.description": "Content is available in multiple languages including Marathi and English. We maintain clear and simple language structure and provide definitions for unusual words and abbreviations.",
  "accessibility.compliance.title": "Compliance Standards",
  "accessibility.compliance.description": "Our website conforms to WCAG 2.1 Level AA guidelines and follows the Government of India's Guidelines for Indian Government Websites (GIGW). We regularly conduct accessibility audits to maintain compliance.",
  "accessibility.contact.title": "Accessibility Support",
  "accessibility.contact.description": "If you encounter any accessibility barriers or have suggestions for improvement, please contact our accessibility team:",
  "accessibility.contact.email": "Email",
  "accessibility.contact.phone": "Phone",

};


// marathi

export const MR = {
  // Header
  "dial.112": "डायल 112",
  "citizen.portal": "नागरिक पोर्टल",
  "e.office": "ई-ऑफिस",
  "nic.email": "एनआयसी ईमेल",
  sss: "एसएसएस",
  "skip.content": "थेट मजकुरावर जा",
  "font.size": "फॉन्ट आकार",
  "high.contrast": "हाय कॉन्ट्रास्ट",
  "light.mode": "लाइट मोड",
  "dark.mode": "डार्क मोड",
  language: "भाषा",
  marathi: "मराठी",
  english: "इंग्रजी",
  "title": "पोलीस दळणवळण आणि माहिती <br/> तंत्रज्ञान विभाग, पुणे",
  //rank
  "backToHome": "मुख्यपृष्ठावर परत जा",
  "ranks.title": "रँक",
  "ranks.subtitle": "पोलीस संप्रेषण आणि माहिती तंत्रज्ञान विभागातील रँक आणि पदनामांची यादी",
  "ranks.seePDF": "संपूर्ण PDF पहा",
  "ranks.rank1.title": "अतिरिक्त DGP आणि संचालक पोलीस संप्रेषण, माहिती तंत्रज्ञान आणि वाहतूक, महाराष्ट्र राज्य, पुणे",
  "ranks.rank1.description": "संपूर्ण विभागाचे नेतृत्व करतो, धोरणात्मक दिशा निश्चित करतो, सर्व युनिटमध्ये समन्वय सुनिश्चित करतो आणि राज्यव्यापी संप्रेषण, आयटी आणि वाहतूक कार्ये देखरेख करतो.",
  "ranks.rank2.title": "उप पोलीस महानिरीक्षक संप्रेषण आणि माहिती तंत्रज्ञान, महाराष्ट्र राज्य, पुणे",
  "ranks.rank2.description": "राज्यव्यापी कार्यप्रदर्शन व्यवस्थापित करण्यासाठी संचालकांची मदत करतो, तांत्रिक संघांचे पर्यवेक्षण करतो आणि धोरणे आणि मानकांचे पालन सुनिश्चित करतो.",
  "ranks.rank3.title": "अतिरिक्त पोलीस आयुक्त संप्रेषण आणि माहिती तंत्रज्ञान, महाराष्ट्र राज्य, मुंबई",
  "ranks.rank3.description": "मुंबई ऑपरेशन्सचे नेतृत्व करतो, गंभीर आयटी इन्फ्रास्ट्रक्चरचे व्यवस्थापन करतो, सुरक्षित संप्रेषण सुनिश्चित करतो आणि स्थानिक कायदा अंमलबजावणी युनिट्ससह समन्वय साधतो.",
  "ranks.rank4.title": "पोलीस अधीक्षक संप्रेषण आणि माहिती तंत्रज्ञान",
  "ranks.rank4.description": "फील्ड युनिट्सचे पर्यवेक्षण करतो, वायरलेस सिस्टीम मॉनिटर करतो, विभागीय क्रियाकलापांचे समन्वयन करतो आणि दैनंदिन कार्यसंचालन सुरळीतपणे सुनिश्चित करतो.",
  "ranks.rank5.title": "उप पोलीस आयुक्त संप्रेषण आणि माहिती तंत्रज्ञान",
  "ranks.rank5.description": "तांत्रिक संघांचे पर्यवेक्षण करतो, ऑपरेशन्सचे व्यवस्थापन करतो आणि आयटी आणि संप्रेषण धोरणांच्या अंमलबजावणीसाठी मार्गदर्शन प्रदान करतो.",
  "ranks.rank6.title": "उप पोलीस अधीक्षक /सहाय्यक पोलीस आयुक्त",
  "ranks.rank6.description": "दैनंदिन तांत्रिक कार्यसंचालन, कर्मचाऱ्यांची नियुक्ती, समस्या निवारण हाताळतो आणि विभागीय प्रोटोकॉलचे पालन सुनिश्चित करतो.",
  "ranks.rank7.title": "पोलीस निरीक्षक (PI)",
  "ranks.rank7.description": "संघांचे पर्यवेक्षण करतो, फील्ड संप्रेषण मॉनिटर करतो, नियमांची अंमलबजावणी करतो आणि वरिष्ठ अधिकाऱ्यांना तांत्रिक समस्यांवर अहवाल देतो.",
  "ranks.rank8.title": "पोलीस उपनिरीक्षक (PSI)",
  "ranks.rank8.description": "वायरलेस नेटवर्क्सचे देखभाल करतो, तपास करण्यासाठी समर्थन देते आणि युनिटमधील प्रभावी संप्रेषण सुनिश्चित करतो.",
  "ranks.rank9.title": "ASI (वरिष्ठ तांत्रिक अधिकारी)",
  "ranks.rank9.description": "तांत्रिक प्रकल्पांचे नेतृत्व करतो, सिस्टम ऑडिट करतो, कनिष्ठ कर्मचाऱ्यांना प्रशिक्षण देतो आणि ऑपरेशन्समध्ये तांत्रिक उत्कृष्टता सुनिश्चित करतो.",
  "ranks.rank10.title": "HC (तांत्रिक अधिकारी)",
  "ranks.rank10.description": "तांत्रिक उपकरणे चालवतो आणि देखभाल करतो, वायरलेस आणि आयटी ऑपरेशन्ससाठी समर्थन देते आणि सतत सेवा सुनिश्चित करतो.",
  "ranks.rank11.title": "ASI (वरिष्ठ तांत्रिक सहाय्यक)",
  "ranks.rank11.description": "तांत्रिक कार्यांमध्ये वरिष्ठ अधिकाऱ्यांना मदत करतो, सिस्टम देखभाल आणि फील्ड युनिट्ससह समन्वय साधतो.",
  "ranks.rank12.title": "HC (तांत्रिक सहाय्यक ग्रेड II)",
  "ranks.rank12.description": "प्रशासकीय समर्थन, तांत्रिक दस्तऐवजीकरण हाताळतो आणि संप्रेषण कार्यांमध्ये सहाय्य करतो.",
  "ranks.rank13.title": "PN (तांत्रिक सहाय्यक ग्रेड I)",
  "ranks.rank13.description": "दैनंदिन तांत्रिक सहाय्यक कार्य करतो, उपकरणे मॉनिटर करतो आणि ऑपरेशन्ससाठी समर्थन देते.",
  "ranks.rank14.title": "PC (तांत्रिक सहाय्यक)",
  "ranks.rank14.description": "पर्यवेक्षणाखाली ऑपरेशन्ससाठी समर्थन देते, संप्रेषण कार्यांमध्ये सहाय्य करते आणि नोंदी राखते.",
  "ranks.rank15.title": "ASI (चालक)",
  "ranks.rank15.description": "उच्चपदस्थ अधिकाऱ्यांसाठी वाहतूक सेवा पुरवते आणि ऑपरेशनल लॉजिस्टिक्ससाठी समर्थन देते.",
  "ranks.rank16.title": "HC (चालक)",
  "ranks.rank16.description": "कर्मचाऱ्यांसाठी आणि उपकरणांसाठी विश्वासार्ह वाहतूक सुनिश्चित करते आणि लॉजिस्टिक नियोजनात मदत करते.",
  "ranks.rank17.title": "PN (चालक)",
  "ranks.rank17.description": "वाहन ऑपरेशन्स आणि विभागातील वाहतूक समन्वयासाठी समर्थन देते.",
  "ranks.rank18.title": "PC (चालक)",
  "ranks.rank18.description": "नियमित चालकीची कर्तव्ये हाताळते, वाहतूक समन्वय आणि कर्मचाऱ्यांची वेळेवर गतिशीलता सुनिश्चित करते.",

  //listofofficer
  "back_to_home": "मुख्यपृष्ठावर परत",
  "export_csv": "CSV निर्यात करा",
  "list_of_officers": "अधिकाऱ्यांची यादी",
  "seniority_ranking_description": "महाराष्ट्र पोलीस कम्युनिकेशन आणि आयटी विभागातील वरिष्ठतेनुसार अधिकारी आणि कर्मचारी क्रमवारी",
  "sr_no": "अनुक्रमांक",
  "full_name": "पूर्ण नाव",
  "designation": "पदनाम",
  "email": "ईमेल",
  "contact": "संपर्क",
  "csv_file_name": "maharashtra_police_employees.csv",
  "previous": "मागील",
  "next": "पुढील",
  "page": "पृष्ठ",
  "of": "चा/ची",
  "emp_1_name": "श्री. दीपक शिवानंद पांडे",
  "emp_1_designation": "ADGP & Dir.PCIT&T",
  "emp_2_name": "श्री. आर. राजा",
  "emp_2_designation": "DIGP(PCIT)/SP",
  "emp_3_name": "श्री. राजेश रामचंद्र बंसोडे",
  "emp_3_designation": "SP(PCIT)",
  "emp_4_name": "श्री. संजय सुभाष चांदखेडे",
  "emp_4_designation": "DYSP(PCIT)",
  "emp_5_name": "श्री. अरविंद ढोंडीबा अलहत",
  "emp_5_designation": "DYSP(PCIT)",
  "emp_6_name": "श्री. सिताराम लक्ष्मण जाधव",
  "emp_6_designation": "DYSP(PCIT)",
  "emp_7_name": "श्री. काशीनाथ मंगाजी उदर",
  "emp_7_designation": "DYSP(PCIT)",
  "emp_8_name": "श्री. शिवप्रसाद गरिबा उइके",
  "emp_8_designation": "DYSP(PCIT)",
  "emp_9_name": "श्री. सुनील विठलराव कुम्भरे",
  "emp_9_designation": "DYSP(PCIT)",
  "emp_10_name": "श्री. नितिन प्रभाकर जोशी",
  "emp_10_designation": "DYSP(PCIT)",
  "emp_11_name": "श्री. रतन खंडेराव ढोकले",
  "emp_11_designation": "PI(PCIT)",
  "emp_12_name": "श्री. कोरे महिंद्र",
  "emp_12_designation": "PI(PCIT)",
  "emp_13_name": "श्री. महेंद्र नारायण भोसले",
  "emp_13_designation": "PI(PCIT)",
  "emp_14_name": "श्री. संदीप प्रभाकर ससाणे",
  "emp_14_designation": "PI(PCIT)",
  "emp_15_name": "श्री. राजाराम दत्तात्रय पोपालघाट",
  "emp_15_designation": "PI(PCIT)",
  "emp_16_name": "श्री. संजय शंकरराव चिंटewar",
  "emp_16_designation": "PI(PCIT)",
  "emp_17_name": "श्री. जितेंद्र भानुजी पारदेशी",
  "emp_17_designation": "PI(PCIT)",
  "emp_18_name": "श्री. दीपक श्रीकृष्ण केळकर",
  "emp_18_designation": "PSI(PCIT)",
  "emp_19_name": "श्री. विक्रम विठलराव तांबरे",
  "emp_19_designation": "PSI(PCIT)",
  "emp_20_name": "श्री. सुनील मोरेश्वर पोते",
  "emp_20_designation": "PSI(PCIT)",

  // Department Info
  "dept.name.marathi": "पोलीस दळणवळण व माहिती तंत्रज्ञान विभाग",
  "dept.name.english": "Police Communication and Information Technology Department",
  "dept.subtitle": "महाराष्ट्र राज्य अधिकृत संकेतस्थळ",

  // Navigation
  "nav.home": "मुख्यपृष्ठ",
  "nav.about": "आमच्याबद्दल",
  "nav.directorDesk": "संचालकांच्या डेस्क वरून",
  "nav.formerDirectors": "माजी संचालक",
  "nav.hierarchy": "पदसोपान",
  "nav.aboutDepartment": "विभागाबद्दल",
  "nav.offices": "मुख्यालयातील कार्यालये",
  "nav.ranks": "पदनामे",
  "nav.welfare": "कल्याणकारी उपक्रम",

  "nav.citizens": "नागरिकांकरिता",
  "nav.policeCorner": "पोलीस कोपरे",
  "nav.pressRelease": "प्रेस प्रकाशन",
  "nav.rti": "माहिती अधिकार (RTI)",
  "nav.gazette": "राजपत्र",
  "nav.officersList": "अधिकाऱ्यांची यादी",
  "nav.promotionOrders": "बढती आदेश",
  "nav.transfers": "बदली",
  "nav.gradationList": "क्रमवारी यादी",
  "nav.strategySupport": "धोरण समर्थन प्रणाली",
  "nav.positiveStories": "सकारात्मक कथा",

  "nav.police_corner": "पोलीस विभाग",
  "nav.tenders": "निविदा यादी",
  "nav.recruitments": "भरती",

  "nav.media": "माध्यमे",
  "nav.gallery": "फोटो गॅलरी",

  "nav.contact": "संपर्क",
  "nav.contactUs": "आमच्याशी संपर्क साधा",

  // Hero Section
  "police.helpline": "पोलीस हेल्पलाईन",
  "medical.helpline": "वैद्यकीय आपत्कालीन सेवा",
  "women.safety": "महिला सुरक्षा हेल्पलाईन",
  "welcome.title": "महाराष्ट्र पोलीस दळणवळण, माहिती तंत्रज्ञान आणि वाहतूक विभागात आपले स्वागत आहे",
  "welcome.message": "संपूर्ण महाराष्ट्रात सार्वजनिक सुरक्षितता वाढवण्यासाठी आणि पोलीस कामकाज अधिक कार्यक्षम करण्यासाठी अत्याधुनिक तंत्रज्ञानाचा वापर करण्यास आम्ही वचनबद्ध आहोत.",
  "director.desk": "संचालकांच्या डेस्क वरून",
  "director.caption": "“आधुनिक दळणवळण आणि माहिती तंत्रज्ञानाद्वारे पोलीस पायाभूत सुविधा आधुनिक करण्याची आमची वचनबद्धता महाराष्ट्राच्या सुरक्षा चौकटीला अधिक बळकटी देत आहे...”",
  "read.more": "अधिक वाचा",

  //welfarre
  "welfare.title": "कल्याणकारी उपक्रम",
  "welfare.accordionTitle": "कल्याणकारी उपक्रम",
  "welfare.viewButton": "पहा",
  "welfare.detailsButton": "तपशील",
  "welfare.item1.title": "संग्रहालय – वायरलेस मधील विकास",
  "welfare.item2.title": "कॅन्टीन – मुक्ताई",
  "welfare.item3.title": "बॅडमिंटन हॉल – संत तुकाराम संकुल",
  "welfare.item4.title": "वरिष्ठ अधिकाऱ्यांचे मेस – ज्ञानेश्वरी",
  "welfare.item5.title": "कनिष्ठ अधिकाऱ्यांचे मेस – संचार",
  "welfare.item6.title": "ओपन संग्रहालय – आर्यभट्ट उद्यान",
  "welfare.item7.title": "परेड ग्राउंड",
  "welfare.item8.title": "सौर विद्युतीकरण प्रकल्प",
  "welfare.item9.title": "पावसाचे पाणी संग्रहण",
  "welfare.item10.title": "महाराष्ट्र पोलीस वायरलेस कल्याण संकुल आणि परिषद केंद्र",

  // Hero slider images
  "hero.modernTech.title": "आधुनिक पोलीस तंत्रज्ञान",
  "hero.modernTech.subtitle": "नवीन उपक्रमांद्वारे सार्वजनिक सुरक्षितता वाढवणे",

  "hero.digitalGovernance.title": "डिजिटल प्रशासन",
  "hero.digitalGovernance.subtitle": "पारदर्शक आणि कार्यक्षम पोलीस सेवा",

  "hero.communityPolicing.title": "समुदाय पोलीसिंग",
  "hero.communityPolicing.subtitle": "तंत्रज्ञानाद्वारे विश्वास निर्माण करणे",

  //ABOUTDEPT
  "hx_back": "मुख्यपृष्ठावर परत",
  "hx_photoAlt": "पोलीस वायरलेसचा इतिहास",
  "hx_title": "पोलीस वायरलेस संप्रेषण विभागाचा इतिहास",
  "hx_intro": "१९४६ मध्ये स्थापन झालेला हा विभाग, दुसऱ्या महायुद्धातील वायरलेस संचांपासून आधुनिक उपग्रह व आयपी आधारित नेटवर्कपर्यंत विकसित झाला आहे, ज्यामुळे महाराष्ट्रभर सुरक्षित व तत्काळ संप्रेषण शक्य झाले.",

  "hx_1946_title": "१९४६ – स्थापना",
  "hx_1946_desc": "पूर्व-स्वातंत्र्य काळात मुंबई येथे विभागाची स्थापना झाली. वायरलेसची सुरुवात दुसऱ्या महायुद्धातील संचांपासून झाली; १३ जिल्हे पुणे मुख्यालयाशी जोडले गेले.",

  "hx_1947_title": "१९४७ – पहिले नेतृत्व",
  "hx_1947_desc": "स्वातंत्र्यानंतर श्री. एन. एम. कामटे हे पहिले विशेष आयजीपी झाले. वायरलेस विभागाचे स्वतंत्र प्रशासन झाले आणि नेतृत्व श्री. एस. एम. नाबर यांनी केले.",

  "hx_tableTitle": "मंजूर पदे",
  "hx_table_sr": "क्रमांक",
  "hx_table_desig": "पदनाम",
  "hx_table_posts": "मंजूर पदसंख्या",
  "hx_prev": "मागील",
  "hx_next": "पुढील",
  "hx_page": "पान",
  "hx_of": "पैकी",
  "hx_summary": "एकूण सारांश:",


  //officerinhq
  "administrative.title": "प्रशासन शाखा",
  "administrative.ministerial": "मंत्रालयीन शाखा",
  "administrative.technical": "तांत्रिक शाखा",
  "administrative.incharge": "प्रभारी :- कार्यालयीन अधीक्षक (OS)",

  "branchA.title": "“अ” शाखा",
  "branchA.item1": "माहिती अधिकार (RTI)",
  "branchA.item2": "वार्षिक प्रशासकीय अहवाल",
  "branchA.item3": "अंदाजपत्रक, वार्षिक तपासणी",
  "branchA.item4": "बी.एम.आय. इ. शासकीय क्वार्टरचे वाटप/ देखभाल / दुरुस्ती",
  "branchA.item5": "एन.ई. लाईन/ वैद्यकीय/ प्रवास भत्ता/ एम.एस.ई.बी./ एम.के.ए.वाय./ टेलिफोन/ एम.टी./ इंधन आदींचे बिल आदेश",

  "branchB.title": "“ब” शाखा",
  "branchB.item1": "कल्याण",
  "branchB.item2": "आयकर",
  "branchB.item3": "जीएसटी",

  "establishment.title": "स्थापना शाखा",
  "establishment.item1": "गोपनीय अहवाल (CRs)",
  "establishment.item2": "विभागीय चौकशा (DEs)",
  "establishment.item3": "बढती",
  "establishment.item4": "बदली",
  "establishment.item5": "इयत्ता ३ व ४ कर्मचाऱ्यांची भरती",

  "accounts.title": "हिशोब शाखा",
  "accounts.item1": "पोलीस अधिकारी व कर्मचारी यांच्या पगाराची बिले",
  "accounts.item2": "सेवा पुस्तिका देखभाल",
  "accounts.item3": "निवृत्तीवेतन प्रकरणे तयार करणे",
  "accounts.item4": "अंदाजपत्रक तयार करणे",
  "accounts.item5": "लेखापरीक्षण अनुपालन",

  "class4.title": "इयत्ता ४ शाखा",
  "class4.item1": "हजेरी नोंदींचे देखभाल",
  "class4.item2": "कर्तव्यांचे वाटप",
  "class4.item3": "कार्यालयीन स्वच्छता व स्वच्छता",
  "class4.item4": "कार्यालयीन वाहनांची देखभाल",

  "technical.title": "तांत्रिक शाखा",
  "technical.incharge": "प्रभारी :- पोलिस रेडिओ अधिकारी (PRO)",

  "wireless.title": "वायरलेस विभाग",
  "wireless.item1": "वायरलेस सेटची देखभाल व कार्यान्वयन",
  "wireless.item2": "वारंवारतेचे वाटप",
  "wireless.item3": "रेडिओ वाहतूक देखरेख",
  "wireless.item4": "वायरलेस उपकरणांची दुरुस्ती",
  "wireless.item5": "नवीन उपकरणांची स्थापना",

  "computer.title": "संगणक विभाग",
  "computer.item1": "संगणक हार्डवेअरची देखभाल",
  "computer.item2": "सॉफ्टवेअर विकास",
  "computer.item3": "डेटाबेस व्यवस्थापन",
  "computer.item4": "नेटवर्क सुरक्षा",
  "computer.item5": "वापरकर्त्यांना प्रशिक्षण व सहाय्य",

  "cipher.title": "सिफर विभाग",
  "cipher.item1": "कोडीत संदेश हाताळणे",
  "cipher.item2": "गोपनीय लेखन तंत्रांचा विकास",
  "cipher.item3": "सिफर कामकाजाचे प्रशिक्षण",

  "training.title": "प्रशिक्षण विभाग",
  "training.item1": "तांत्रिक कर्मचाऱ्यांसाठी प्रशिक्षण आयोजित करणे",
  "training.item2": "नवीन संचार तंत्रज्ञानावर कार्यशाळा",
  "training.item3": "प्रशिक्षण संस्थांसह सहयोग",

  "stores.title": "साठा विभाग",
  "stores.item1": "वायरलेस उपकरणांची खरेदी",
  "stores.item2": "साठ्याचे व्यवस्थापन",
  "stores.item3": "जुनी/अकार्यक्षम वस्तूंची विल्हेवाट",

  "traffic.title": "वाहतूक शाखा",
  "traffic.incharge": "उपविभागीय पोलिस अधिकारी (वाहतूक)",
  "traffic.item1": "६४ पोलनेट स्टेशन, ४६ एचएफ स्टेशन, ६४ टीएपीची तपासणी",
  "traffic.item2": "व्हीव्हीआयपी, मंत्री, अधिकारी यांचे कॉल साइन तयार करणे",
  "traffic.item3": "आयटी प्राविण्य परीक्षा (लेखी/प्रायोगिक) आयोजित व पर्यवेक्षण",
  "traffic.item4": "सेंट्रल चेक ऑफिस, पुणे येथून वाहतूक प्रकरणांचे पर्यवेक्षण",
  "traffic.item5": "व्हीएचएफ चॅनलवरील सुरक्षा उल्लंघन प्रकरणांची तपासणी",

  //rank
  "ranks_back": "मुख्यपृष्ठावर परत",
  "ranks_title": "पदनाम",
  "ranks_subtitle": "पोलीस संप्रेषण आणि माहिती तंत्रज्ञान विभागातील पदनाम व अधिकारांची यादी",
  "ranks_pdfButton": "संपूर्ण PDF पहा",

  "ranks_1_rank": "अ‍ॅडिशनल डीजीपी व संचालक पोलीस संप्रेषण, माहिती तंत्रज्ञान व वाहतूक, एम.एस. पुणे",
  "ranks_1_description": "संपूर्ण विभागाचे नेतृत्व करतो, धोरणात्मक दिशा निश्चित करतो, सर्व युनिट्समध्ये समन्वय सुनिश्चित करतो आणि संप्रेषण, आयटी व वाहतूक कार्ये राज्यव्यापी पाहतो.",

  "ranks_2_rank": "उप-आयुक्त पोलीस संप्रेषण व माहिती तंत्रज्ञान, एम.एस. पुणे",
  "ranks_2_description": "संचालकांना राज्यव्यापी कार्ये व्यवस्थापित करण्यात मदत करतो, तांत्रिक टीम्सचे निरीक्षण करतो व धोरण व मानकांचे पालन सुनिश्चित करतो.",

  "ranks_3_rank": "अ‍ॅडिशनल कमिशनर पोलीस संप्रेषण व माहिती तंत्रज्ञान, एम.एस. मुंबई",
  "ranks_3_description": "मुंबई कार्ये नेतृत्व करतो, महत्वाच्या आयटी प्रणालीचे व्यवस्थापन करतो, सुरक्षित संप्रेषण सुनिश्चित करतो व स्थानिक पोलिस युनिट्ससह समन्वय साधतो.",

  "ranks_4_rank": "सुप्रिंटेंडंट ऑफ पोलीस संप्रेषण व माहिती तंत्रज्ञान",
  "ranks_4_description": "फील्ड युनिट्सवर देखरेख करतो, वायरलेस प्रणालींचे निरीक्षण करतो, विभागीय क्रियाकलाप समन्वयित करतो आणि दैनंदिन कार्य सुरळीत पार पाडतो.",

  "ranks_5_rank": "उप आयुक्त पोलीस संप्रेषण व माहिती तंत्रज्ञान",
  "ranks_5_description": "तांत्रिक टीम्सवर देखरेख करतो, कार्ये व्यवस्थापित करतो आणि आयटी व संप्रेषण धोरण अंमलात आणण्यास मार्गदर्शन करतो.",

  "ranks_6_rank": "उप सुपरिंटेंडंट ऑफ पोलीस / सहाय्यक आयुक्त पोलीस",
  "ranks_6_description": "दैनंदिन तांत्रिक कार्ये हाताळतो, कर्मचाऱ्यांचे वितरण करतो, समस्या निवारण करतो व विभागीय प्रोटोकॉलचे पालन सुनिश्चित करतो.",

  "ranks_7_rank": "पोलीस निरीक्षक (PI)",
  "ranks_7_description": "टीम्सचे निरीक्षण करतो, फील्ड संप्रेषणावर देखरेख करतो, नियमांचे पालन करतो आणि तांत्रिक समस्यांची वरिष्ठ अधिकारीांना माहिती देतो.",

  "ranks_8_rank": "पोलीस उप-निरीक्षक (PSI)",
  "ranks_8_description": "वायरलेस नेटवर्क राखतो, तपासांमध्ये मदत करतो व युनिटमधील प्रभावी संप्रेषण सुनिश्चित करतो.",

  "ranks_9_rank": "ASI (वरिष्ठ तांत्रिक अधिकारी)",
  "ranks_9_description": "तांत्रिक प्रकल्पांचे नेतृत्व करतो, प्रणालींचे ऑडिट करतो, कनिष्ठ कर्मचार्‍यांचे प्रशिक्षण करतो व कार्यांमध्ये तांत्रिक उत्कृष्टता सुनिश्चित करतो.",

  "ranks_10_rank": "HC (तांत्रिक अधिकारी)",
  "ranks_10_description": "तांत्रिक उपकरण चालवतो व देखभाल करतो, वायरलेस व आयटी कार्यांना समर्थन देतो व सेवा सातत्यपूर्ण सुनिश्चित करतो.",

  "ranks_11_rank": "ASI (वरिष्ठ तांत्रिक सहाय्यक)",
  "ranks_11_description": "वरिष्ठ अधिकाऱ्यांना तांत्रिक कार्यात मदत करतो, प्रणाली देखभाल करतो व फील्ड युनिट्ससह समन्वय साधतो.",

  "ranks_12_rank": "HC (तांत्रिक सहाय्यक ग्रेड II)",
  "ranks_12_description": "प्रशासकीय समर्थन करतो, तांत्रिक दस्तऐवजीकरण हाताळतो आणि संप्रेषण कार्यात सहाय्य करतो.",

  "ranks_13_rank": "PN (तांत्रिक सहाय्यक ग्रेड I)",
  "ranks_13_description": "दैनंदिन तांत्रिक सहाय्य करतो, उपकरणे तपासतो आणि कार्यांना समर्थन करतो.",

  "ranks_14_rank": "PC (तांत्रिक सहाय्यक)",
  "ranks_14_description": "पर्यवेक्षणाखाली कार्यांस समर्थन करतो, संप्रेषण कार्यात सहाय्य करतो आणि नोंदी ठेवतो.",

  "ranks_15_rank": "ASI (ड्रायव्हर)",
  "ranks_15_description": "उच्च पदस्थ अधिकाऱ्यांसाठी वाहतूक पुरवतो आणि ऑपरेशनल लॉजिस्टिकला समर्थन करतो.",

  "ranks_16_rank": "HC (ड्रायव्हर)",
  "ranks_16_description": "कर्मचारी व उपकरणांसाठी विश्वासार्ह वाहतूक सुनिश्चित करतो आणि लॉजिस्टिक नियोजनात मदत करतो.",

  "ranks_17_rank": "PN (ड्रायव्हर)",
  "ranks_17_description": "विभागातील वाहन संचालन व वाहतूक समन्वयात मदत करतो.",

  "ranks_18_rank": "PC (ड्रायव्हर)",
  "ranks_18_description": "दैनंदिन ड्रायव्हिंग कर्तव्ये हाताळतो, वाहतूक समन्वय करतो आणि कर्मचाऱ्यांच्या वेळेवर हालचाली सुनिश्चित करतो.",



  //OFFICERSINNHQ
  "oh_back": "मुख्यपृष्ठावर परत",
  "oh_title": "मुख्यालयातील अधिकारी",

  "oh_admin_title": "प्रशासनिक कार्यालय",
  "oh_admin_incharge": "ऑफिस अधीक्षक (OS)",
  "oh_admin_A_title": "“A” शाखा",
  "oh_admin_A_item1": "RTI",
  "oh_admin_A_item2": "वार्षिक प्रशासन अहवाल",
  "oh_admin_A_item3": "बजेट, वार्षिक तपासणी",
  "oh_admin_A_item4": "BMI इत्यादी सरकारी निवास वितरण / देखभाल / दुरुस्ती",
  "oh_admin_A_item5": "NE लाईन / वैद्यकीय / TA / MSEB / MKAY / दूरध्वनी / MT / इंधन / इत्यादी बिल भरण्याचे आदेश",
  "oh_admin_B_title": "“B” शाखा",
  "oh_admin_B_item1": "कल्याण",
  "oh_admin_B_item2": "आयकर",
  "oh_admin_B_item3": "GST",
  "oh_admin_E_title": "“E” शाखा",
  "oh_admin_E_item1": "MAT प्रकरणे",
  "oh_admin_E_item2": "वायरलेस अधिकारी / कर्मचारी चौकशी",
  "oh_admin_E_item3": "PC ते PSI ग्रेडेशन यादी",
  "oh_admin_E_item4": "बढती व स्थानांतरण",
  "oh_admin_E_item5": "सेवा पत्रांची तयारी",
  "oh_admin_E_item6": "रिक्त जागांची माहिती अद्ययावत ठेवणे",
  "oh_admin_E_item7": "वर्गीकरण / कौशल्य परीक्षांचे वेळापत्रक तयार करणे",
  "oh_admin_E_item8": "भरती / RR प्रक्रिया हाताळणे व फॉलो-अप",
  "oh_admin_D_title": "“D” शाखा",
  "oh_admin_D_item1": "GEM (NIC पोर्टल) मार्फत स्पेअर्स/अॅक्सेसरीज खरेदी",
  "oh_admin_D_item2": "DGP MS मुंबईद्वारे वायरलेस उपकरण खरेदीसाठी टेंडर प्रक्रिया",

  "oh_tech_title": "तांत्रिक शाखा",
  "oh_tech_incharge": "DYSP (Admin)",
  "oh_tech_item1": "प्रशासनिक व तांत्रिक शाखांचा दैनंदिन कामकाजाचे निरीक्षण करणे",
  "oh_tech_item2": "प्रशासनिक शाखा: A, B, D, E, लेखापरीक्षा",
  "oh_tech_item3": "तांत्रिक शाखा: बंदोबस्त, नियोजन, परवाना, कल्याण, गृह PI, SSS",
  "oh_tech_item4": "बंदोबस्त शाखा: मनुष्यबळ व उपकरणे पुरवठा करणे, नोंदी ठेवणे, तपासणी वेळापत्रके राखणे",
  "oh_tech_item5": "नियोजन शाखा: प्रस्ताव तयार करणे, बैठकांचे आयोजन करणे, Pol-4 व DGP मुंबई सह समन्वय",
  "oh_tech_item6": "गृह PI: MT विभाग, MAT प्रकरणे, RTI काम हाताळणे",
  "oh_tech_item7": "कल्याण शाखा: ज्ञानेश्वरी वरिष्ठ अधिकाऱ्यांचे मेस, संचार हॉटेल इत्यादीवर देखरेख",
  "oh_tech_item8": "SSS शाखा: पोलिस संचारासाठी चाचणी, विकास व सुधारणा",

  "oh_dev_title": "विकास विभाग",
  "oh_dev_item1": "कंप्युटर विभाग: तांत्रिक तपशील, NIC ईमेल, CIPHER देखभाल, व्हिडिओ कॉन्फरन्स, e-Office अंमलबजावणी",
  "oh_dev_item2": "रेडिओ संचार विभाग: वायरलेस सेटची दुरुस्ती, नाकारणे, चाचणी, रिपीटर्स",
  "oh_dev_item3": "लाइन संचार विभाग: दूरध्वनी एक्स्चेंज, IP/Digital युनिट्स, केबल देखभाल, नवीन खरेदीचे मूल्यमापन",
  "oh_dev_item4": "इलेक्ट्रिकल विभाग: चार्जर, इन्व्हर्टर, UPS, DG सेट्स, सौर चार्जर, बॅटरी देखभाल व मूल्यमापन",
  "oh_dev_item5": "इंस्टॉलेशन शाखा: DG सेट्स, स्ट्रीटलाईट्स, एअर कंडिशनर्स देखभाल, स्थानिक खरेदी, पाणी व वीज बिल",
  "oh_dev_item6": "स्टोअर विभाग: स्टोअर साहित्य हाताळणी, नोंदी ठेवणे, चाचणी अहवाल व नमुना नोंदी",

  "oh_vsat_title": "V-SAT विभाग",
  "oh_vsat_incharge": "DYSP",
  "oh_vsat_item1": "महाराष्ट्रातील सर्व Polnet स्टेशनचा दैनिक स्थितीचे निरीक्षण",
  "oh_vsat_item2": "Polnet युनिटसाठी तांत्रिक मार्गदर्शन (DCPW, नवी दिल्ली सह समन्वय)",
  "oh_vsat_item3": "Polnet HQ पुणे स्टेशनचे सुरळीत संचालन सुनिश्चित करणे",
  "oh_vsat_item4": "Polnet व CCTV उपकरणासाठी तांत्रिक तपशील तयार करणे",

  //DIRECTONFO
  "a1.back": "मुख्य पृष्ठावर परत",

  "a2.desk": "संचालकांचे मनोगत",
  "a2.name": "श्री. दीपक शिवानंद पांडे",
  "a2.desg": "पोलीस महासंचालक (अतिरिक्त) व संचालक",
  "a2.dept": "पोलीस संचार व माहिती तंत्रज्ञान विभाग",
  "a2.loc": "महाराष्ट्र राज्य, पुणे",

  "b1.intro": "पोलीस वायरलेस विभाग (आताचा पोलीस संचार व माहिती तंत्रज्ञान विभाग) हा महाराष्ट्र राज्य पोलीस दलाच्या संचार व्यवस्थेची जबाबदारी सांभाळतो. यात रेडिओ फ्रिक्वेन्सीचे व्यवस्थापन, अधिकारी तैनात करणे व क्षेत्रातील युनिट्समध्ये सुरक्षित आणि कार्यक्षम संचार सुनिश्चित करणे यांचा समावेश होतो.",
  "b1.hl": " अखंडित 24×7 संचार ",
  "b1.intro2": "प्रणाली आमच्या विभागामार्फत पुरवली जाते.",
  "b1.role": "पोलीस संचार व माहिती तंत्रज्ञान विभाग पोलीसिंगमध्ये प्रभावी संचार आणि समन्वय साधण्यात महत्त्वाची भूमिका बजावतो. या विभागाची प्रमुख कार्ये खालीलप्रमाणे आहेत:",

  "c1.f1.t": "रिअल-टाइम संचार",
  "c1.f1.d": "अधिकारी आणि नियंत्रण कक्ष यांच्यात त्वरित संपर्क साधतो.",
  "c1.f2.t": "स्थितिजन्य जागरूकता",
  "c1.f2.d": "सद्यस्थितीबाबत अद्ययावत माहिती पुरवतो ज्यामुळे निर्णय अधिक चांगले होतात.",
  "c1.f3.t": "आपत्कालीन प्रतिसाद",
  "c1.f3.d": "आपत्कालीन परिस्थितीत तातडीने तैनाती सक्षम करतो.",
  "c1.f4.t": "डेटा प्रसारण",
  "c1.f4.d": "महत्त्वाची माहिती सुरक्षितपणे शेअर करण्यास मदत करतो.",
  "c1.f5.t": "सुरक्षा व संरक्षकता",
  "c1.f5.d": "संवेदनशील माहिती व अधिकारी यांची सुरक्षा सुनिश्चित करतो.",

  "b1.crisis": "कोयना भूकंप (1967) आणि किल्लारी भूकंप (1993) यांनी महाराष्ट्रात मोठी हानी केली. मुंबई पूर (2005) आणि 26/11 दहशतवादी हल्ल्याने संचाराचे महत्त्व अधोरेखित केले. अशा आपत्तीच्या काळात खाजगी नेटवर्क ठप्प झाले असताना वायरलेस प्रणालीमुळे पोलिस सतत जोडले गेले आणि जीव वाचविण्यासाठी समन्वय साधला गेला.",
  "b1.conc": "प्रभावी वायरलेस संचार हे सार्वजनिक सुरक्षितता व कार्यकुशल पोलीसिंगचे कणा आहे.",

  // Director Info
  "director.name": "श्री. दीपक शिवानंद पांडे (IPS)",
  "director.rank": "अतिरिक्त पोलीस महासंचालक व संचालक,",
  "director.designation": "पोलीस दळणवळण, माहिती तंत्रज्ञान आणि वाहतूक विभाग, महाराष्ट्र राज्य, पुणे.",

  //FORMAERDIRECOTR
  "fd.back": "मागे",
  "fd.title": "विभागाचे माजी संचालक",

  "fd.d1.name": "श्री. सुनील रमनंद आयपीएस",
  "fd.d1.designation": "अतिरिक्त महानिरीक्षक",
  "fd.d1.tenure": "२०२१-२०२४",

  "fd.d2.name": "श्री. रितेश कुमार आयपीएस",
  "fd.d2.designation": "अतिरिक्त महानिरीक्षक",
  "fd.d2.tenure": "२०१६-२०२१",

  "fd.d3.name": "श्री. जगन्नाथ आयपीएस",
  "fd.d3.designation": "अतिरिक्त महानिरीक्षक",
  "fd.d3.tenure": "२०१४-२०१६",

  "fd.d4.name": "श्री. सुरेश कक्कड आयपीएस",
  "fd.d4.designation": "अतिरिक्त महानिरीक्षक",
  "fd.d4.tenure": "२०१२-२०१४",

  "fd.d5.name": "श्री. पी. पी. पी. शर्मा आयपीएस",
  "fd.d5.designation": "अतिरिक्त महानिरीक्षक",
  "fd.d5.tenure": "२००८-२०११",

  "fd.d6.name": "श्री. बी. टी. नघिंगलोवा आयपीएस",
  "fd.d6.designation": "अतिरिक्त महानिरीक्षक",
  "fd.d6.tenure": "२००७-२००८",

  "fd.d7.name": "श्री. पी. टी. लोहार आयपीएस",
  "fd.d7.designation": "अतिरिक्त महानिरीक्षक",
  "fd.d7.tenure": "२००४-२००७",

  "fd.d8.name": "श्री. पी. के. जोशी आयपीएस",
  "fd.d8.designation": "विशेष पोलीस महानिरीक्षक २०००-२००३ | अतिरिक्त महानिरीक्षक २००३-२००४",
  "fd.d8.tenure": "२०००-२००४",

  "fd.d9.name": "श्री. ए. डी. जोग एसपीएस",
  "fd.d9.designation": "उपमहानिरीक्षक १९७९-१९८७ | विशेष पोलीस महानिरीक्षक १९८९-१९९९",
  "fd.d9.tenure": "१९७९-१९९९",

  "fd.d10.name": "श्री. एस. एम. नाबर",
  "fd.d10.designation": "पोलीस अधीक्षक १९४८-१९६८ | उपमहानिरीक्षक १९६८-१९७८",
  "fd.d10.tenure": "१९४८-१९७८",

  "fd.d11.name": "श्री. एल. ए. पॅडन रो आयपी",
  "fd.d11.designation": "एसपी एम. टी. आणि डब्ल्यू/एल",
  "fd.d11.tenure": "१९४७-१९४८",

  "fd.d12.name": "श्री. ई. ए. डॉडवेल आयपी",
  "fd.d12.designation": "एसपी एम. टी. आणि डब्ल्यू/एल",
  "fd.d12.tenure": "१९४६-१९४७",



  //HEIRRACHY
  "h1.back": "मागे",
  "h1.title": "आरेखन",
  "h1.alt": "पदसोपान चार्ट",


  // Emergency Contacts
  "emergency_contacts": "Emergency Contacts",
  "emergency.police": "पोलीस आपत्कालीन सेवा",
  "emergency.fire": "अग्निशमन आपत्कालीन सेवा",
  "emergency.ambulance": "रुग्णवाहिका",
  "emergency.disaster": "आपत्ती व्यवस्थापन",
  "emergency.women": "महिला हेल्पलाईन",
  "emergency.child": "बाल हेल्पलाईन",
  "emergency.single": "एकत्रित आपत्कालीन क्रमांक",

  "type.police": "पोलीस",
  "type.fire": "अग्निशमन",
  "type.medical": "वैद्यकीय",
  "type.disaster": "आपत्ती",
  "type.women": "महिला सुरक्षा",
  "type.child": "बालसंगोपन",
  "type.allInOne": "सर्व-इन-वन",

  // Government Updates
  "govt.updates": "शासन अद्यतने",
  bulletins: "परिपत्रके / आदेश / सूचना",
  "tenders.section": "टेन्डर्स",
  "view.all": "सर्व पहा",
  "bulletin.cybercrimePortal": "PP RESULT RM, ELE., WO – 2024",
  "bulletin.digitalEvidence": "AANDYANKIT KASHAT UPSHTIT RAHANEBABAT",
  "bulletin.emergencyProtocol": "KARYMUKT KARNEBABAT",
  "bulletin.auditResults": "SHUDHIPATAK GT – (PC-ASI)-2024",

  "badge.new": "नवीन",
  "badge.important": "महत्वाचे",
  "badge.update": "अद्यतन",
  "badge.report": "अहवाल",
  // tenders
  "tender.communicationEquipment": "दळणवळण उपकरणांचा पुरवठा आणि स्थापना",
  "tender.mobileApp": "नागरिक सेवांसाठी मोबाइल विकास",
  "tender.serverMaintenance": "सर्व्हर इन्फ्रास्ट्रक्चरची वार्षिक देखभाल",

  "tender.status.open": "सुरू आहे",
  "tender.status.closingSoon": "लवकरच बंद होणार",


  // Events
  "latest.events": "ताज्या घटना",
  "photo.gallery": "फोटो गॅलरी",
  "view.all.events": "सर्व घटना पहा",
  "view.gallery": "गॅलरी पहा",
  "event.pcit.upgrades": "पीसीआयटीमध्ये स्वातंत्र्य दिनाचे उत्सव",
  "event.marvel.aiProject": "पीसीआयटीमध्ये प्रजासत्ताक दिनाचे उत्सव",
  "event.dial112": "डायल ११२ एकत्रित आपत्कालीन प्रतिसाद",
  "event.cyber.centerLaunch": "सायबर कमांड आणि नियंत्रण केंद्र उद्घाटन",

  "event.location.headquarters": "मुख्यालय",
  "event.location.statewide": "संपूर्ण राज्यात",
  "event.location.maharashtra": "मुख्यालय",
  "event.location.mumbai": "मुंबई",
  "gallery.videoAvailable": "व्हिडिओ गॅलरी उपलब्ध आहे",
  "gallery.viewAllPhotos": "सर्व फोटो पहा",


  // Emergency Helplines 
  "emergency.message": "आपत्कालीन परिस्थितीत त्वरित मदतीसाठी या क्रमांकांवर कॉल करा",

  "helpline.child": "बाल हेल्पलाईन",
  "helpline.senior": "वरिष्ठ नागरिक हेल्पलाईन",
  "helpline.roadAccident": "रस्ता अपघात आपत्कालीन सेवा",
  "helpline.fire": "अग्निशमन सेवा",
  "helpline.disaster": "आपत्ती व्यवस्थापन",
  "helpline.antiCorruption": "भ्रष्टाचार विरोधी हेल्पलाईन",
  "emergency.helpline": "आपत्कालीन हेल्पलाईन्स",

  "metro.helpline": "मुंबई मेट्रो",
  "rest.helpline": "महाराष्ट्रातील इतर भाग",
  "helpline.tapToCall": "कॉल करण्यासाठी टॅप करा",

  "additionalHelplines.header": "इतर महत्त्वाचे हेल्पलाईन क्रमांक",

  "important.note.title": "महत्त्वाची नोंद:",
  "important.note.message": "हे हेल्पलाईन क्रमांक २४/७ उपलब्ध आहेत. गैर-आपत्कालीन पोलीस सेवांसाठी, आपण आपल्या जवळच्या पोलीस ठाण्याला भेट देऊ शकता किंवा आमच्या ऑनलाइन पोर्टलचा उपयोग करू शकता.",

  "emergency.tips.title": "आपत्कालीन परिस्थितीत",
  "emergency.tips.item1": "शांत राहा आणि स्पष्ट बोला",
  "emergency.tips.item2": "आपली अचूक ठिकाण माहिती द्या",
  "emergency.tips.item3": "आपत्कालीन परिस्थितीचे स्वरूप स्पष्ट करा",
  "emergency.tips.item4": "ऑपरेटरच्या सूचनांचे पालन करा",
  "emergency.tips.item5": "आपला फोन पूर्ण चार्जेड आणि सहज उपलब्ध ठेवा",


  "smart.features.title": "स्मार्ट वैशिष्ट्ये",
  "smart.features.item1": "उच्चार/ऐकण्यात अडचणी असणाऱ्यांसाठी 112 वर SMS",
  "smart.features.item2": "त्वरित प्रतिसादासाठी ठिकाण ट्रॅकिंग",
  "smart.features.item3": "अनेक भाषा समर्थन उपलब्ध",
  "smart.features.item4": "आपत्कालीन सेवा एकत्रीकरण",


  // goverment links


  "acb_maharashtra": "भ्रष्टाचार विरोधी विभाग, महाराष्ट्र राज्य",
  "acb_full_name": "भ्रष्टाचार विरोधी विभाग महाराष्ट्राची वेबसाइट पहा",
  "mpa_nashik": "महाराष्ट्र पोलीस अकादमी",
  "mpa_full_name": "महाराष्ट्र पोलीस अकादमीची वेबसाइट पहा",
  "aaple_sarkar": "आपले सरकार - महाराष्ट्र शासन पोर्टल",
  "aaple_sarkar_desc": "आपले सरकार महाराष्ट्र शासन सेवा पोर्टल पहा",
  "maharashtra_police": "महाराष्ट्र पोलीस",
  "maharashtra_police_desc": "महाराष्ट्र पोलीस अधिकृत वेबसाइट पहा",
  "startup_india": "स्टार्टअप इंडिया उपक्रम",
  "startup_india_desc": "स्टार्टअप इंडिया सरकारी उपक्रमाची वेबसाइट पहा",
  "digital_india": "डिजिटल इंडिया उपक्रम",
  "digital_india_desc": "डिजिटल इंडिया सरकारी उपक्रमाची वेबसाइट पहा",
  "government_partners": "सरकारी भागीदार आणि संबंधित वेबसाइट्स",
  "carousel_instructions": "सरकारी भागीदारांच्या वेबसाइट लिंकवर नेव्हिगेट करण्यासाठी अ‍ॅरो की वापरा",

  // Footer
  "quick.links": "त्वरित दुवे",
  "important.links": "महत्वाचे दुवे",
  "contact.info": "संपर्क माहिती",
  "visitor.stats": "भेट देणाऱ्यांची आकडेवारी",
  address: "पत्ता",
  phone: "फोन",
  email1: "ईमेल",
  copyright:
    "© 2025 पोलीस दळणवळण व माहिती तंत्रज्ञान विभाग, महाराष्ट्र राज्य. सर्व हक्क राखीव.",
  "developed.by": "डिझाइन व विकसित: ड्रीमकेअर सोल्यूशन्स",
  "dept.address": "पोलीस दळणवळण व आय.टी. विभाग,<br />महाराष्ट्र राज्य पोलीस मुख्यालय,<br />मुंबई - ४००००१",


  // Helpline
  "police.100": "पोलीस - 100/112",
  "medical.108": "वैद्यकीय - 108",
  "women.103": "महिला सुरक्षा - 103/1091",
  "maha.police": "महाराष्ट्र पोलीस",
  "rti": "माहितीचा अधिकार",
  "public.grievances": "सार्वजनिक तक्रारी",
  "footer.privacyPolicy": "गोपनीयता धोरण",
  "footer.termsOfUse": "वापरण्याचे नियम",
  "footer.accessibility": "सुलभता",

  // Press Release Page
  "back.home": "मुख्यपृष्ठावर परत",
  "press.title": "प्रेस विज्ञप्ती",
  "press.subtitle": "महाराष्ट्र पोलीस वायरलेस विभागातील सकारात्मक घडामोडी आणि चालू प्रकल्प",
  "press.tech.title": "तांत्रिक उन्नयन",
  "press.tech.description": "पोलीस दळणवळण व माहिती तंत्रज्ञान विभागामध्ये स्वातंत्र्य दिन उत्साहात साजरा करण्यात आला. विभागातील अधिकारी व कर्मचारी यांनी देशभक्तिपूर्ण वातावरणात ध्वजारोहण, राष्ट्रगीत आणि विविध सांस्कृतिक कार्यक्रमांमध्ये सहभाग घेतला. या उत्सवातून देशभक्ती, एकात्मता आणि तांत्रिक प्रगतीबद्दल जागरूकता निर्माण करण्यात आली.",
  "press.ai.title": "कृत्रिम बुद्धिमत्ता आधारित पोलिसिंग - MARVEL प्रकल्प",
  "press.ai.description": "पोलीस दळणवळण व माहिती तंत्रज्ञान विभागामध्ये प्रजासत्ताक दिन उत्साहात साजरा करण्यात आला. अधिकारी व कर्मचारी यांनी ध्वजारोहण, राष्ट्रगीत व देशभक्तिपर कार्यक्रमांमध्ये सहभाग घेतला. या निमित्ताने संविधान मूल्ये, देशभक्ती आणि एकात्मतेचा संदेश देण्यात आला.",
  "press.emergency.title": "सुधारित आणीबाणी प्रतिसाद - डायल 112",
  "press.emergency.description": "'डायल 112' आणीबाणी प्रणाली पोलीस (100), अग्निशामक (101) आणि एम्ब्युलन्स (108) सेवा एकाच क्रमांकावर एकत्रित करते. अॅडव्हान्स्ड ट्रॅकिंग आणि डिस्पॅच तंत्रज्ञानाचा वापर करून, प्रतिसाद वेळ मोठ्या प्रमाणात कमी होतो, जीवन वाचवते आणि सार्वजनिक सुरक्षा सुधारते.",
  "press.cyber.title": "नवीन सायबर कमांड सेंटर",
  "press.cyber.description": "ऑक्टोबर 2024 मध्ये, एक नवीन सायबर कमांड अँड कंट्रोल सेंटर सुरू करण्यात आला. अॅडव्हान्स्ड फॉरेन्सिक साधने आणि AI-आधारित धोका शोधासह सुसज्ज, ते पोलिसांना सायबर गुन्ह्यांविरुद्ध कार्यक्षमतेने लढा देण्यास आणि नागरिकांसाठी आणि गंभीर पायाभूत सुविधांसाठी डिजिटल सुरक्षा सुनिश्चित करण्यास सक्षम करते.",

  // RTI Page
  "rti.title": "माहितीचा अधिकार (आरटीआय)",
  "rti.subtitle": "माहितीचा अधिकार कायद्याखाली नागरिकांसाठी माहिती आणि प्रक्रिया",
  "rti.pio.title": "लोक माहिती अधिकारी (PIO) तपशील",
  "rti.pio.description": "पोलीस संप्रेषण आणि आयटी विभागातील नियुक्त PIO आणि अपीलीय प्राधिकरणांची संपर्क माहिती येथे प्रदान केली आहे. नागरिक आरटीआय अर्ज सादर करण्यासाठी किंवा स्पष्टीकरण घेण्यासाठी थेट संपर्क करू शकतात.",
  "rti.procedure.title": "आरटीआय अर्ज प्रक्रिया",
  "rti.procedure.description": "आरटीआय अर्ज भरण्यासाठी चरण-दर-चरण मार्गदर्शक, योग्य स्वरूप, आवश्यक तपशील आणि लागू फी समाविष्ट आहे. वेगवान प्रक्रियेसाठी सर्व फील्ड योग्यरित्या भरल्याचे सुनिश्चित करा.",
  "rti.portal.title": "ऑनलाइन आरटीआय पोर्टल लिंक",
  "rti.portal.description": "अधिकृत पोर्टलद्वारे इलेक्ट्रॉनिकपणे आरटीआय अर्ज सबमिट करा. महाराष्ट्र आरटीआय पोर्टल आणि भारत सरकारच्या आरटीआय ऑनलाइन पोर्टलचा नागरिक सोयीसाठी दुवा दिला आहे.",
  "rti.frequent.title": "वारंवार विचारली जाणारी माहिती",
  "rti.frequent.description": "संघटनात्मक रचना, अंदाजपत्रक तपशील, नागरिक चार्टर आणि विभागीय मॅन्युअल सारख्या सामान्यपणे विचारल्या जाणाऱ्या दस्तऐवजांमध्ये प्रवेश. यामुळे पारदर्शकता सुधारते आणि माहिती पुनर्प्राप्ती सुलभ होते.",
  "rti.manual.title": "आरटीआय कायदा मॅन्युअल",
  "rti.manual.description": "संदर्भासाठी संपूर्ण आरटीआय कायदा, 2005 आणि अधिकृत मार्गदर्शक तत्त्वे डाउनलोड किंवा पहा. नागरिकांना कायद्याखालील त्यांचे हक्क आणि जबाबदाऱ्यांशी परिचित होण्यास प्रोत्साहित केले जाते.",
  "rti.appeal.title": "अपील प्रक्रिया",
  "rti.appeal.description": "अर्जदार प्रतिसादाने असमाधानी असल्यास, निर्धारित वेळेच्या आत अपील प्रक्रिया अनुसरण करा. पहिल्या आणि द्वितीय अपील सादर करण्याच्या तपशिलासह, अपीलीय प्राधिकरणांची संपर्क माहिती प्रदान केली आहे.",


  // Tenders Page
  "tenders.title": "टेंडर आणि खरेदी",
  "tenders.subtitle": "महाराष्ट्र पोलीस वायरलेस विभागासाठी अधिकृत खरेदी सूचना आणि कराराच्या संधी",
  "tenders.active.title": "सक्रिय टेंडर",
  "tenders.archived.title": "संग्रहित / पूर्ण झालेले टेंडर",
  "tenders.procurement.title": "टेंडर संबंधित माहिती",
  "tenders.ref": "टेंडर संदर्भ",
  "tenders.deadline": "अंतिम मुदत",
  "tenders.closedOn": "बंद झाला",
  "tenders.viewDocument": "टेंडर दस्तऐवज पहा",

  // Active Tenders
  "tenders.active.radios.title": "डिजिटल मोबाईल रेडिओची खरेदी",
  "tenders.active.radios.description": "राज्यव्यापी पोलीस संप्रेषणासाठी उच्च-कार्यक्षमतेच्या डिजिटल मोबाईल रेडिओची पुरवठा.",

  // Archived Tenders
  "tenders.archived.spares.title": "वायरलेस उपकरणे स्पेअर भाग",
  "tenders.archived.computers.title": "संगणक आणि नेटवर्किंग उपकरणे",

  // Procurement Info
  "tenders.procurement.general.title": "सामान्य खरेदी तपशील",
  "tenders.procurement.general.description": "सर्व खरेदी प्रक्रिया 'डी' शाखेद्वारे हाताळल्या जातात, ज्यामध्ये GEM पोर्टलद्वारे स्पेअर भाग आणि अॅक्सेसरीजची खरेदी समाविष्ट आहे.",
  "tenders.procurement.technical.title": "तांत्रिक वैशिष्ट्ये",
  "tenders.procurement.technical.description": "डिजिटल मोबाईल रेडिओ, रिपीटर, अँटेना, संगणक आणि टेलिफोन एक्सचेंज सारख्या उपकरणांची वैशिष्ट्ये आरआण्डडी विभागाद्वारे तयार आणि मूल्यांकन केली जातात.",
  "tenders.procurement.auction.title": "लिलाव सूचना",
  "tenders.procurement.auction.description": "केंद्रीय स्टोअरद्वारे चालवल्या जाणाऱ्या निकामी किंवा सेवा अयोग्य उपकरणे (वायरलेस सेट, बॅटरी) यांच्या लिलावावरील माहिती.",

  // Recruitments Page
  "recruit.title": "भरती",
  "recruit.subtitle": "महाराष्ट्र पोलीस वायरलेस विभागातील सध्याच्या आणि आगामी नोकरीच्या संधींबद्दल माहिती",
  "recruit.notifications.title": "भरती सूचना",
  "recruit.notifications.description": "विभागातील सध्याच्या आणि आगामी नोकरीच्या जागांसाठी अधिकृत जाहिराती, ज्यामध्ये ASI, HC, PC, तांत्रिक सहाय्यक आणि चालक यासारख्या पदांचा समावेश आहे. योग्य भूमिकांसाठी अर्ज करण्यासाठी अद्ययावत रहा.",
  "recruit.forms.title": "अर्ज फॉर्म",
  "recruit.forms.description": "विभागीय रिक्त जागांसाठी अर्ज सादर करण्यासाठी दुवे आणि डाउनलोड करण्यायोग्य फॉर्म. जेथे लागू असेल तेथे ऑनलाइन सबमिशन पोर्टल देखील प्रदान केले आहेत.",
  "recruit.exams.title": "परीक्षा वेळापत्रक",
  "recruit.exams.description": "विविध भरती मोहिमांसाठी लेखी परीक्षा, प्रावीण्य परीक्षा आणि व्यावहारिक मूल्यांकनांच्या तारखा आणि वेळापत्रक.",
  "recruit.results.title": "निकाल",
  "recruit.results.description": "पूर्ण झालेल्या भरतींसाठी योग्यता यादी आणि अंतिम निवड निकाल, जसे की 'PP RESULT RM, ELE., WO – 2024'.",
  "recruit.training.title": "प्रशिक्षण तपशील",
  "recruit.training.description": "निवड झालेल्या कॅडेट्ससाठी प्रशिक्षण कार्यक्रमांबद्दल माहिती, ज्यामध्ये DySP, PSI, ASI/RM, HC/वायरलेस ऑपरेटर, HC/इलेक्ट्रिशियन आणि PC/कार्यशाळा हँड यांच्या मूलभूत प्रशिक्षणाचा समावेश आहे.",
  "recruit.eligibility.title": "पात्रता निकष",
  "recruit.eligibility.description": "विविध पदांसाठी शैक्षणिक पात्रता, वयोमर्यादा आणि शारीरिक आवश्यकता जेणेकरून सर्व अर्जदार विभागीय मानकांपूर्ण करतील.",
  "recruit.proficiency.title": "प्रावीण्य / वर्गीकरण परीक्षा",
  "recruit.proficiency.description": "अंतर्गत परीक्षांसाठी सूचना ज्या पदोन्नतीत मदत करतात, जसे की वायरलेस ऑपरेटर परीक्षा आणि विभागीय कर्मचाऱ्यांसाठी वर्गीकरण चाचण्या.",
  // Gallery Page
  "gallery.title": "फोटो गॅलरी",
  "gallery.image1.caption": "डॉ. एपीजे अब्दुल कलाम इनोवेशन सेंटर उद्घाटन",
  "gallery.image2.caption": "स्वातंत्र्यदिन साजरे",
  "gallery.image3.caption": "अशोक जोग व्याख्यानगृह उद्घाटन",
  "gallery.image4.caption": "महानिरीक्षक उद्घाटन",



  // Contact Page
  "contact.title": "आमच्याशी संपर्क साधा",
  "contact.subtitle": "फोन, ईमेल द्वारे किंवा आमच्या कार्यालयाला भेट देऊन आमच्याशी संपर्क साधा",
  "contact.address.title": "कार्यालयाचा पत्ता",
  "contact.address.line1": "पोलीस संप्रेषण आणि माहिती तंत्रज्ञान विभाग",
  "contact.address.line2": "महाराष्ट्र राज्य पुणे",
  "contact.address.line3": "डॉ. होमी भाभा रोड, चव्हाणनगर",
  "contact.address.line4": "पुणे – ४११००८, महाराष्ट्र, भारत",
  "contact.phone.title": "दूरध्वनी",
  "contact.phone.number": "०२०-२५६५२५०५",
  "contact.email.title": "ईमेल",
  "contact.email.address": "dir.polwireless.pune@mahapolice.gov.in",
  "contact.map.title": "नकाशावर आम्हाला शोधा",

  // Government Publications Page
  "pubs.title": "सरकारी प्रकाशने आणि अधिसूचना",
  "pubs.subtitle": "महाराष्ट्र पोलीस संप्रेषण आणि आयटी विभागाद्वारे जारी केलेल्या अधिकृत घोषणा, ठराव, परिपत्रक आणि टेंडरमध्ये प्रवेश",
  "pubs.gazette.title": "राजपत्र अधिसूचना",
  "pubs.gazette.description": "महाराष्ट्र सरकारी राजपत्रात प्रकाशित झालेल्या अधिकृत घोषणा, नियुक्त्या आणि धोरणातील बदल. नागरिक आणि कर्मचारी सरकारी आणि विभागीय घडामोडींबद्दल माहिती ठेवण्यासाठी अधिसूचनांमध्ये प्रवेश घेऊ शकतात.",
  "pubs.orders.title": "सरकारी आदेश (GRs)",
  "pubs.orders.description": "पोलीस संप्रेषण आणि आयटी विभागाशी संबंधित सरकारी ठरावांची प्रती. हे आदेश पारदर्शकता सुनिश्चित करतात आणि कार्यसंचालन, कर्मचारी व्यवस्थापन आणि धोरण अंमलबजावणीसाठी अधिकृत निर्देश प्रदान करतात.",
  "pubs.circulars.title": "परिपत्रक",
  "pubs.circulars.description": "पोलीस महासंचालक (DGP) किंवा गृह विभागाद्वारे जारी केलेली अधिकृत परिपत्रके, जी विभागीय कार्यसंचालन आणि कर्मचाऱ्यांसाठी मार्गदर्शक तत्त्वे, सूचना आणि अद्यतने प्रदान करतात.",
  "pubs.notifications.title": "अधिसूचना",
  "pubs.notifications.description": "प्रशासकीय बदल, नियम किंवा नियमांसंबंधी सार्वजनिक सूचना. ह्या अधिसूचना नागरिक आणि कर्मचारी नवीन प्रोटोकॉल किंवा धोरणांमधील सुधारणांबद्दल जागरूक आहेत याची खात्री करतात.",
  "pubs.tenders.title": "टेंडर सूचना",
  "pubs.tenders.description": "विभागीय खरेदी आणि सेवांशी संबंधित टेंडरच्या अधिकृत घोषणा. काही टेंडर स्वतंत्र विभागात सूचीबद्ध केले असले तरी, पारदर्शकता आणि प्रवेशासाठी मुख्य सूचना येथे प्रदान केल्या आहेत.",

  // Privacy Policy Page
  "privacy.title": "गोपनीयता धोरण",
  "privacy.subtitle": "तुमची वैयक्तिक माहिती संरक्षण आणि डेटा सुरक्षा सुनिश्चित करणे",
  "privacy.departmentInfo": "पोलीस संप्रेषण आणि माहिती तंत्रज्ञान विभाग, पुणे | अतिरिक्त पोलीस महासंचालक आणि संचालक, पोलीस संप्रेषण, माहिती तंत्रज्ञान आणि परिवहन विभाग, महाराष्ट्र राज्य, पुणे",
  "privacy.introduction.title": "परिचय",
  "privacy.introduction.description": "पोलीस संप्रेषण आणि माहिती तंत्रज्ञान विभाग सर्व वापरकर्त्यांच्या वैयक्तिक माहितीची गोपनीयता आणि सुरक्षा संरक्षणासाठी वचनबद्ध आहे. हे गोपनीयता धोरण आमच्या सेवा आणि डिजिटल प्लॅटफॉर्मशी संवाद साधताना आम्ही तुमचा डेटा कसा संकलित, वापर आणि संरक्षित करतो याची रूपरेषा दर्शवते.",
  "privacy.dataCollection.title": "आम्ही कोणती माहिती संकलित करतो",
  "privacy.dataCollection.description": "आम्ही आवश्यक वैयक्तिक माहिती संकलित करतो ज्यामध्ये नाव, संपर्क तपशील, ओळख दस्तऐवज आणि सेवा-संबंधित डेटा समाविष्ट आहे. ही माहिती अधिकृत फॉर्म, डिजिटल प्लॅटफॉर्म आणि सेवा वितरणादरम्यान कार्यक्षम संप्रेषण आणि सेवा पुरवठा सुनिश्चित करण्यासाठी संकलित केली जाते.",
  "privacy.dataUsage.title": "आम्ही तुमची माहिती कशी वापरतो",
  "privacy.dataUsage.description": "तुमची माहिती पोलीस सेवा पुरवण्यासाठी, आणीबाणी प्रतिसाद, संप्रेषण हेतू आणि आमच्या सेवा सुधारण्यासाठी वापरली जाते. आम्ही डेटाची प्रक्रिया केवळ कायदेशीर हेतूंसाठी आणि लागू कायदे आणि नियमांच्या अनुपालनात करतो.",
  "privacy.dataSharing.title": "माहिती सामायिकरण",
  "privacy.dataSharing.description": "कायद्यानुसार आवश्यक असल्यास किंवा सार्वजनिक सुरक्षेच्या हेतूंसाठी आम्ही इतर सरकारी एजन्सी, कायदा अंमलबजावणी संस्था आणि आणीबाणी सेवांसह माहिती सामायिक करू शकतो. डेटा व्यावसायिक हेतूंसाठी तृतीय पक्षांना कधीही विकला किंवा सामायिक केला जात नाही.",
  "privacy.dataRetention.title": "डेटा राखणे",
  "privacy.dataRetention.description": "आम्ही वैयक्तिक माहिती केवळ तेव्हाच ठेवतो जेव्हा ती संकलित केलेल्या हेतूंची पूर्तता करणे, कायदेशीर बंधनांचे पालन करणे, विवाद सोडवणे आणि सरकारी नियमांनुसार आमच्या करारांची अंमलबजावणी करणे आवश्यक असते.",
  "privacy.userRights.title": "तुमचे हक्क",
  "privacy.userRights.description": "तुमच्याकडे तुमच्या वैयक्तिक माहितीमध्ये प्रवेश, दुरुस्ती किंवा हटवण्याची विनंती करण्याचा अधिकार आहे. तुमच्याकडे काही प्रक्रिया क्रियाकलापांना प्रतिबंधित किंवा विरोध करण्याचा अधिकार देखील असू शकतो. कोणत्याही गोपनीयता-संबंधित चिंतांसाठी आमच्या डेटा संरक्षण अधिकाऱ्याशी संपर्क साधा.",
  "privacy.security.title": "डेटा सुरक्षा",
  "privacy.security.description": "तुमच्या वैयक्तिक माहितीचे अनधिकृत प्रवेश, बदल, प्रकटीकरण किंवा नाशापासून संरक्षण करण्यासाठी आम्ही योग्य तांत्रिक आणि संघटनात्मक उपाय लागू करतो. आमचे सुरक्षा प्रोटोकॉल सरकारी सुरक्षा मानकांशी सुसंगत आहेत.",
  "privacy.changes.title": "धोरण अद्यतने",
  "privacy.changes.description": "आमच्या पद्धतींमधील किंवा कायदेशीर आवश्यकतांमधील बदल प्रतिबिंबित करण्यासाठी आम्ही हे गोपनीयता धोरण नियतकालिकरित्या अद्यतनित करू शकतो. अद्यतनित धोरण प्रभावी तारखेसह आमच्या वेबसाइटवर पोस्ट केले जाईल. आम्ही तुम्हाला हे धोरण नियमितपणे तपासण्याची शिफारस करतो.",
  "privacy.contact.title": "संपर्क माहिती",
  "privacy.contact.description": "या गोपनीयता धोरणासंबंधी किंवा आमच्या डेटा पद्धतींसंबंधी कोणत्याही प्रश्न किंवा चिंतांसाठी, कृपया आमच्या डेटा संरक्षण अधिकाऱ्याशी संपर्क साधा: पोलीस संप्रेषण आणि आयटी विभाग, पुणे. ईमेल: dpo-pcit@mahapolice.gov.in | फोन: +91-20-2612-XXXX",

  // Terms of Use Page
  "terms.title": "वापराच्या अटी",
  "terms.subtitle": "महाराष्ट्र पोलीस संप्रेषण आणि आयटी विभाग वेबसाइट वापरण्यासाठी अधिकृत अटी आणि नियम",
  "terms.deptInfo": "पोलीस संप्रेषण आणि माहिती तंत्रज्ञान विभाग, पुणे. अतिरिक्त पोलीस महासंचालक आणि संचालक, पोलीस संप्रेषण, माहिती तंत्रज्ञान आणि परिवहन विभाग, महाराष्ट्र राज्य, पुणे.",
  "terms.acceptance.title": "अटींची स्वीकृती",
  "terms.acceptance.description": "हे वेबसाइट access करून आणि वापरून, तुम्ही या वापराच्या अटी स्वीकारता आणि त्यांना बांधील राहण्यास सहमती दर्शवता. जर तुम्ही या अटींशी सहमत नसाल, तर कृपया आमचे वेबसाइट वापरणे टाळा. ह्या अटी सर्व भेट देणाऱ्यांना, वापरकर्त्यांना आणि इतरांना लागू होतात जे सेवा access करतात किंवा वापरतात.",
  "terms.usage.title": "परवानगीयुक्त वापर",
  "terms.usage.description": "हे वेबसाइट पोलीस सेवा, माहिती access आणि नागरी सेवांशी संबंधित कायदेशीर हेतूंसाठी आहे. वापरकर्ते वैयक्तिक, अ-व्यावसायिक हेतूंसाठी सामग्री access आणि वापरू शकतात. कोणताही अनधिकृत वापर, ज्यामध्ये हैकिंग, डेटा स्क्रॅपिंग किंवा दुर्भावनापूर्ण क्रियाकलाप यांचा समावेश आहे पण त्यापुरता मर्यादित नाही, काटेकोरपणे प्रतिबंधित आहे.",
  "terms.security.title": "सुरक्षा तरतुदी",
  "terms.security.description": "वापरकर्त्यांना या वेबसाइटची सुरक्षा समझोता करण्याचा प्रयत्न करणे प्रतिबंधित आहे, ज्यामध्ये सिस्टममध्ये अनधिकृत प्रवेश, डेटा व्यत्यय किंवा दुर्भावनापूर्ण कोड सादर करणे यांचा समावेश आहे. कोणत्याही संशयास्पद क्रियाकलापांची त्वरित वेबसाइट प्रशासकांना किंवा संबंधित प्राधिकरणांना नोंदवली पाहिजे.",
  "terms.liability.title": "जबाबदारीची मर्यादा",
  "terms.liability.description": "हे वेबसाइट वापरण्याच्या किंवा वापरण्यास अक्षम होण्याच्या परिणामी होणाऱ्या कोणत्याही थेट, अप्रत्यक्ष, आकस्मिक, विशेष किंवा परिणामी नुकसानीसाठी महाराष्ट्र पोलीस विभाग जबाबदार राहणार नाही. आम्ही अचूक माहिती राखण्याचा प्रयत्न करत असताना, आम्ही सामग्रीची पूर्णता किंवा अचूकता हमी देत नाही.",
  "terms.privacy.title": "गोपनीयता धोरण",
  "terms.privacy.description": "या वेबसाइटचा वापर आमच्या गोपनीयता धोरणाच्या अधीन आहे, जे आम्ही तुमची वैयक्तिक माहिती कशी गोळा करतो, वापरतो आणि संरक्षण करतो हे स्पष्ट करते. हे वेबसाइट वापरून, तुम्ही गोपनीयता धोरणात वर्णन केल्याप्रमाणे माहिती गोळा करण्यास आणि वापरण्यास संमती दर्शवता.",
  "terms.conduct.title": "वापरकर्ता वर्तन",
  "terms.conduct.description": "वापरकर्त्यांनी अशी कोणतीही क्रिया करू नये जी वेबसाइटची कार्यक्षमता बाधित किंवा व्यत्यय आणते. यामध्ये दुर्भावनापूर्ण सामग्री अपलोड करणे, स्पॅमिंग किंवा इतर कोणतीही क्रिया समाविष्ट आहे जी वेबसाइटची अखंडता किंवा कार्यप्रदर्शन समझोता करू शकते.",
  "terms.changes.title": "अटींमध्ये बदल",
  "terms.changes.description": "पूर्वसूचना न देता कोणत्याही वेळी या अटी सुधारण्याचा किंवा बदलण्याचा आम्हाला अधिकार राखून ठेवला आहे. बदलांसाठी या अटींचे नियतकालिक पुनरावलोकन करणे तुमची जबाबदारी आहे. कोणत्याही सुधारणांनंतर वेबसाइटचा सतत वापर त्या बदलांची स्वीकृती दर्शवतो.",
  "terms.contact.title": "संपर्क माहिती",
  "terms.contact.description": "वापराच्या या अटींबद्दल कोणत्याही प्रश्नांसाठी, कृपया पोलीस संप्रेषण आणि आयटी विभागाशी pcit@mahapolice.gov.in येथे किंवा +91-22-2262-1234 या क्रमांकावर संपर्क साधा.",


  // Accessibility Page
  "accessibility.title": "प्रवेशयोग्यता विधान",
  "accessibility.subtitle": "सर्व नागरिकांसाठी डिजिटल सेवांची समान प्रवेशयोग्यता सुनिश्चित करणे",
  "accessibility.deptInfo.title": "पोलीस संप्रेषण आणि माहिती तंत्रज्ञान विभाग",
  "accessibility.deptInfo.description": "अतिरिक्त पोलीस महासंचालक आणि संचालक, पोलीस संप्रेषण, माहिती तंत्रज्ञान आणि परिवहन विभाग, महाराष्ट्र राज्य, पुणे अपंग व्यक्तींसाठी डिजिटल प्रवेशयोग्यता सुनिश्चित करण्यासाठी वचनबद्ध आहे. आम्ही सर्वांसाठी वापरकर्ता अनुभव सतत सुधारत आहोत आणि संबंधित प्रवेशयोग्यता मानकांना लागू करत आहोत.",
  "accessibility.visual.title": "दृश्य प्रवेशयोग्यता",
  "accessibility.visual.description": "आमची वेबसाइट स्क्रीन रीडरला समर्थन देते, उच्च कॉन्ट्रास्ट मोड, आकार बदलता येणारा मजकूर आणि प्रतिमांसाठी पर्यायी मजकूर प्रदान करते. वापरकर्ते त्यांच्या आवडीनुसार फॉंट आकार आणि कॉन्ट्रास्ट सेटिंग्ज समायोजित करू शकतात.",
  "accessibility.auditory.title": "श्रवण प्रवेशयोग्यता",
  "accessibility.auditory.description": "आम्ही ऑडिओ सामग्रीसाठी Transcripts, व्हिडिओसाठी बंद मथळे आणि ऑडिओ सूचनांसाठी दृश्य पर्याय प्रदान करतो. सर्व मल्टीमीडिया सामग्री श्रवणदोष असलेल्या वापरकर्त्यांसाठी प्रवेशयोग्य असण्यासाठी डिझाइन केली आहे.",
  "accessibility.motor.title": "मोटर प्रवेशयोग्यता",
  "accessibility.motor.description": "वेबसाइट कीबोर्ड नेव्हिगेशन, व्हॉइस कमांड आणि सहाय्यक तंत्रज्ञानासह विविध इनपुट पद्धतींना समर्थन देते. आम्ही फॉर्म पूर्ण करण्यासाठी पुरेसा वेळ सुनिश्चित करतो आणि स्पष्ट फोकस संकेतक प्रदान करतो.",
  "accessibility.keyboard.title": "कीबोर्ड नेव्हिगेशन",
  "accessibility.keyboard.description": "सर्व कार्यक्षमता कीबोर्ड इंटरफेसद्वारे उपलब्ध आहे, वैयक्तिक कीस्ट्रोक्ससाठी विशिष्ट वेळेची आवश्यकता नसते. वेबसाइट तार्किक टॅब क्रमाचे अनुसरण करते आणि नेव्हिगेशन दुवे वगळण्याची सुविधा प्रदान करते.",
  "accessibility.language.title": "भाषा समर्थन",
  "accessibility.language.description": "सामग्री मराठी आणि इंग्रजी यासहित अनेक भाषांमध्ये उपलब्ध आहे. आम्ही स्पष्ट आणि साधी भाषा रचना राखतो आणि असामान्य शब्द आणि संक्षेपांसाठी व्याख्या प्रदान करतो.",
  "accessibility.compliance.title": "अनुपालन मानके",
  "accessibility.compliance.description": "आमची वेबसाइट WCAG 2.1 लेव्हल AA मार्गदर्शक तत्त्वांशी सुसंगत आहे आणि भारत सरकारच्या भारतीय सरकारी वेबसाइट्ससाठी मार्गदर्शक तत्त्वांचे (GIGW) अनुसरण करते. आम्ही अनुपालन राखण्यासाठी नियमितपणे प्रवेशयोग्यता ऑडिट करतो.",
  "accessibility.contact.title": "प्रवेशयोग्यता समर्थन",
  "accessibility.contact.description": "जर तुम्हाला कोणतीही प्रवेशयोग्यता अडथळे येत असल्यास किंवा सुधारणेसाठी सूचना असल्यास, कृपया आमच्या प्रवेशयोग्यता संघाशी संपर्क साधा:",
  "accessibility.contact.email": "ईमेल",
  "accessibility.contact.phone": "फोन",

};
